/* ============================================================================
   Literature — Milestone 3. The canon: the books and the landmark papers that
   built quantitative finance over the last ~75 years. Curated, accurately cited.
   Each book carries a short tagline (`note`) and 2–3 "why it matters" bullets
   (`why`) surfaced in the expandable card. Drop a cover image at
   public/covers/<cover> and set `cover` to show real artwork; otherwise the card
   renders a styled typographic cover. Papers that map onto our research articles
   carry an `article` slug so the library cross-links into the case studies.
   ========================================================================== */

export interface Book {
  title: string;
  author: string;
  year: number;
  note: string;       // one-line tagline (teaser / first "why" point)
  why: string[];      // 2–3 bullets revealed in "Why it matters"
  cover?: string;     // optional /covers/<file>; falls back to a typographic cover
  coverW?: number;    // intrinsic cover width  (px) — reserves true aspect ratio
  coverH?: number;    // intrinsic cover height (px)
  citation?: string;  // full APA citation, shown in the hover detail layer
}

export interface BookGroup {
  theme: string;
  blurb: string;
  books: Book[];
}

export interface Paper {
  year: number;
  authors: string;
  title: string;
  journal: string;
  note: string;
  article?: string; // slug in /research/<article>
}

/* --------------------------------------------------------------- books -- */

export const BOOK_GROUPS: BookGroup[] = [
  {
    theme: "Foundations",
    blurb: "The mathematics, probability and stochastic calculus everything else is built on.",
    books: [
      {
        title: "Financial calculus: An introduction to derivative pricing",
        author: "Baxter & Rennie",
        year: 1996,
        note: "A famous textbook and classic guide in quantitative finance.",
        citation: "Baxter, M., & Rennie, A. (1996). Financial calculus: An introduction to derivative pricing. Cambridge University Press.",
        why: [
          "A famous textbook and classic guide in quantitative finance.",
          "Explains the complex math used to find fair prices for financial derivatives.",
          "Bridges high-level mathematical theory and practical use on trading desks.",
          "Authors: Martin Baxter and Andrew Rennie, industry derivatives quants.",
        ],
        cover: "baxter-financial-calculus.jpg",
        coverW: 855,
        coverH: 1360,
      },
      {
        title: "The concepts and practice of mathematical finance",
        author: "Joshi",
        year: 2008,
        note: "A highly respected guide to quantitative finance.",
        citation: "Joshi, M. S. (2008). The concepts and practice of mathematical finance (2nd ed.). Cambridge University Press.",
        why: [
          "A highly respected guide to quantitative finance.",
          "Bridges the gap between complex mathematical theory and practical trading-floor applications.",
          "Strong emphasis on how models are actually implemented.",
          "Author: Mark Joshi, former bank quant (RBS) and professor at the University of Melbourne.",
        ],
        cover: "joshi-the-concepts-and-practice-of-mathematical-.jpg",
        coverW: 897,
        coverH: 1360,
      },
      {
        title: "Stochastic calculus for finance II: Continuous-time models",
        author: "Shreve",
        year: 2004,
        note: "Highly popular text from Carnegie Mellon’s renowned computational finance master’s program.",
        citation: "Shreve, S. E. (2004). Stochastic calculus for finance II: Continuous-time models. Springer.",
        why: [
          "Highly popular text from Carnegie Mellon’s renowned computational finance master’s program.",
          "A core guide for quants and financial engineers.",
          "Models stock prices, interest rates, and options under randomness over time.",
          "Author: Steven Shreve, Carnegie Mellon professor and co-founder of its computational-finance master’s.",
        ],
        cover: "shreve-stochastic-calculus-for-finance-ii.jpg",
        coverW: 827,
        coverH: 1245,
      },
      {
        title: "Arbitrage theory in continuous time",
        author: "Björk",
        year: 2020,
        note: "The standard graduate text on arbitrage pricing in continuous time.",
        citation: "Björk, T. (2020). Arbitrage theory in continuous time (4th ed.). Oxford University Press.",
        why: [
          "The standard graduate text on arbitrage pricing in continuous time.",
          "Develops martingale and measure-change methods rigorously yet readably.",
          "Bridges pure stochastic calculus and derivative pricing.",
          "Author: Tomas Björk, professor at the Stockholm School of Economics.",
        ],
        cover: "bj-rk-arbitrage-theory-in-continuous-time.jpg",
        coverW: 856,
        coverH: 1360,
      },
      {
        title: "Brownian motion and stochastic calculus",
        author: "Karatzas & Shreve",
        year: 1991,
        note: "The definitive mathematical reference on Brownian motion and stochastic calculus.",
        citation: "Karatzas, I., & Shreve, S. E. (1991). Brownian motion and stochastic calculus (2nd ed.). Springer.",
        why: [
          "The definitive mathematical reference on Brownian motion and stochastic calculus.",
          "Aimed at advanced readers.",
          "Supplies the rigorous foundations under every continuous-time pricing model.",
          "Authors: Ioannis Karatzas (Columbia) and Steven Shreve (Carnegie Mellon), leading probabilists.",
        ],
        cover: "karatzas-brownian-motion-and-stochastic-calculus.jpg",
        coverW: 827,
        coverH: 1254,
      },
      {
        title: "Statistical inference",
        author: "Casella & Berger",
        year: 2002,
        note: "The standard graduate text on mathematical statistics and inference.",
        citation: "Casella, G., & Berger, R. L. (2002). Statistical inference (2nd ed.). Duxbury.",
        why: [
          "The standard graduate text on mathematical statistics and inference.",
          "Rigorous foundation in estimation, hypothesis testing, and likelihood.",
          "The statistics backbone behind econometrics and model validation.",
          "Authors: George Casella and Roger Berger, eminent academic statisticians.",
        ],
        cover: "casella-statistical-inference.jpg",
        coverW: 350,
        coverH: 514,
      },
      {
        title: "Analysis of financial time series",
        author: "Tsay",
        year: 2010,
        note: "The standard applied text on financial time series.",
        citation: "Tsay, R. S. (2010). Analysis of financial time series (3rd ed.). Wiley.",
        why: [
          "The standard applied text on financial time series.",
          "Covers volatility modeling (GARCH), return dynamics, and multivariate methods.",
          "A staple of empirical quant research.",
          "Author: Ruey Tsay, professor of econometrics and statistics at Chicago Booth.",
        ],
        cover: "tsay-analysis-of-financial-time-series.jpg",
        coverW: 978,
        coverH: 1500,
      },
      {
        title: "Time series analysis",
        author: "Hamilton",
        year: 1994,
        note: "The authoritative reference on time-series econometrics.",
        citation: "Hamilton, J. D. (1994). Time series analysis. Princeton University Press.",
        why: [
          "The authoritative reference on time-series econometrics.",
          "Go-to source for ARMA, state-space, VAR, and regime-switching models.",
          "Dense and comprehensive.",
          "Author: James Hamilton, professor at UC San Diego; a leading time-series econometrician.",
        ],
        cover: "hamilton-time-series-analysis.jpg",
        coverW: 956,
        coverH: 1500,
      },
      {
        title: "A first course in probability",
        author: "Ross",
        year: 2019,
        note: "A classic first course in probability used worldwide.",
        citation: "Ross, S. M. (2019). A first course in probability (10th ed.). Pearson.",
        why: [
          "A classic first course in probability used worldwide.",
          "Builds core intuition for randomness, distributions, and expectation.",
          "Foundational for every quantitative discipline.",
          "Author: Sheldon Ross, professor at USC and a prolific applied-probability author.",
        ],
        cover: "ross-a-first-course-in-probability.jpg",
        coverW: 370,
        coverH: 474,
      },
      {
        title: "Introduction to probability",
        author: "Blitzstein & Hwang",
        year: 2019,
        note: "Modern, intuition-first text from Harvard’s popular Stat 110 course.",
        citation: "Blitzstein, J. K., & Hwang, J. (2019). Introduction to probability (2nd ed.). Chapman & Hall/CRC.",
        why: [
          "Modern, intuition-first text from Harvard’s popular Stat 110 course.",
          "Makes conditioning, distributions, and stochastic thinking understandable.",
          "Widely praised for clarity.",
          "Authors: Joe Blitzstein (Harvard, Stat 110) and Jessica Hwang (Stanford).",
        ],
        cover: "blitzstein-introduction-to-probability.jpg",
        coverW: 949,
        coverH: 1400,
      },
      {
        title: "The econometrics of financial markets",
        author: "Campbell & MacKinlay",
        year: 1997,
        note: "The foundational graduate text in financial econometrics.",
        citation: "Campbell, J. Y., Lo, A. W., & MacKinlay, A. C. (1997). The econometrics of financial markets. Princeton University Press.",
        why: [
          "The foundational graduate text in financial econometrics.",
          "Links asset-pricing theory to empirical testing.",
          "Standard reference for factor models and market-efficiency research.",
          "Authors: John Campbell (Harvard), Andrew Lo (MIT Sloan), and Craig MacKinlay (Wharton).",
        ],
        cover: "campbell-the-econometrics-of-financial-markets.jpg",
        coverW: 856,
        coverH: 1360,
      },
      {
        title: "Econometric analysis",
        author: "Greene",
        year: 2018,
        note: "The encyclopedic graduate reference in econometrics.",
        citation: "Greene, W. H. (2018). Econometric analysis (8th ed.). Pearson.",
        why: [
          "The encyclopedic graduate reference in econometrics.",
          "One of the most-cited works in economics (90,000+ citations).",
          "Comprehensive across MLE, GMM, time series, panel, and limited-dependent models.",
          "Author: William Greene, professor at NYU Stern.",
        ],
        cover: "greene-econometric-analysis.jpg",
        coverW: 332,
        coverH: 400,
      },
    ],
  },
  {
    theme: "Fixed Income & Interest-Rate Modeling",
    blurb: "Bonds, the yield curve, and the models that price interest-rate risk.",
    books: [
      {
        title: "Fixed income analysis",
        author: "Fabozzi",
        year: 2022,
        note: "The CFA-series standard on fixed income.",
        citation: "Fabozzi, F. J. (2022). Fixed income analysis (5th ed.). Wiley.",
        why: [
          "The CFA-series standard on fixed income.",
          "Covers bond math, term structure, credit, and securitized products.",
          "Institutional entry point to rates and credit analysis.",
          "Author: Frank Fabozzi, editor of the CFA fixed-income curriculum and the most prolific fixed-income author.",
        ],
        cover: "fabozzi-fixed-income-analysis.jpg",
        coverW: 637,
        coverH: 900,
      },
      {
        title: "Fixed income securities: Tools for today’s markets",
        author: "Tuckman & Serrat",
        year: 2022,
        note: "Modern, practitioner-oriented bestseller on fixed income.",
        citation: "Tuckman, B., & Serrat, A. (2022). Fixed income securities: Tools for today’s markets (4th ed.). Wiley.",
        why: [
          "Modern, practitioner-oriented bestseller on fixed income.",
          "Covers arbitrage pricing, duration/convexity, and curve construction.",
          "Reflects the tools used on rates desks today.",
          "Authors: Bruce Tuckman (NYU Stern; ex-Lehman/CME) and Angel Serrat (ex-JPMorgan PM).",
        ],
        cover: "tuckman-fixed-income-securities.jpg",
        coverW: 1014,
        coverH: 1500,
      },
      {
        title: "Fixed income securities: Valuation, risk, and risk management",
        author: "Veronesi",
        year: 2010,
        note: "Bridges bond fundamentals and quantitative rates modeling.",
        citation: "Veronesi, P. (2010). Fixed income securities: Valuation, risk, and risk management. Wiley.",
        why: [
          "Bridges bond fundamentals and quantitative rates modeling.",
          "Strong on valuation and risk management.",
          "Covers derivatives and structured products.",
          "Author: Pietro Veronesi, professor of finance at Chicago Booth.",
        ],
        cover: "veronesi-fixed-income-securities.jpg",
        coverW: 1000,
        coverH: 1427,
      },
      {
        title: "Bond pricing and yield curve modeling: A structural approach",
        author: "Rebonato",
        year: 2018,
        note: "A modern, authoritative treatment of the yield curve.",
        citation: "Rebonato, R. (2018). Bond pricing and yield curve modeling: A structural approach. Cambridge University Press.",
        why: [
          "A modern, authoritative treatment of the yield curve.",
          "A structural approach from a leading rates quant.",
          "Bridges heavy rates models and how curves are actually built.",
          "Author: Riccardo Rebonato, EDHEC professor; former head of rates/FX quant research at PIMCO and RBS.",
        ],
        cover: "rebonato-bond-pricing-and-yield-curve-modeling.jpg",
        coverW: 1003,
        coverH: 1500,
      },
      {
        title: "Interest rate models—Theory and practice: With smile, inflation and credit",
        author: "Brigo & Mercurio",
        year: 2006,
        note: "The definitive practitioner reference for interest-rate models.",
        citation: "Brigo, D., & Mercurio, F. (2006). Interest rate models—Theory and practice: With smile, inflation and credit (2nd ed.). Springer.",
        why: [
          "The definitive practitioner reference for interest-rate models.",
          "Covers short-rate and market (LIBOR/HJM) models in depth.",
          "Detailed on calibration and smile-consistent pricing.",
          "Authors: Damiano Brigo (Imperial College) and Fabio Mercurio (head of quant analytics, Bloomberg).",
        ],
        cover: "brigo-interest-rate-models.jpg",
        coverW: 827,
        coverH: 1257,
      },
    ],
  },
  {
    theme: "Derivatives, Options & Volatility",
    blurb: "Options, futures and the volatility surface — how derivatives are priced and hedged.",
    books: [
      {
        title: "Options, futures, and other derivatives",
        author: "Hull",
        year: 2021,
        note: "The most widely used derivatives textbook in the world.",
        citation: "Hull, J. C. (2021). Options, futures, and other derivatives (11th ed.). Pearson.",
        why: [
          "The most widely used derivatives textbook in the world.",
          "The common language of options, futures, swaps, and risk-neutral pricing.",
          "Standard for students and practitioners alike.",
          "Author: John Hull, professor at the University of Toronto’s Rotman School.",
        ],
        cover: "hull-options-futures-and-other-derivatives.jpg",
        coverW: 484,
        coverH: 613,
      },
      {
        title: "Option volatility and pricing: Advanced trading strategies and techniques",
        author: "Natenberg",
        year: 2015,
        note: "The classic on options from a trader’s perspective.",
        citation: "Natenberg, S. (2015). Option volatility and pricing: Advanced trading strategies and techniques (2nd ed.). McGraw-Hill.",
        why: [
          "The classic on options from a trader’s perspective.",
          "Builds intuition for the Greeks, volatility, and spreads.",
          "Light on heavy math; a perennial desk favorite.",
          "Author: Sheldon Natenberg, veteran options trader and educator (Chicago).",
        ],
        cover: "natenberg-option-volatility-and-pricing.jpg",
        coverW: 662,
        coverH: 1000,
      },
      {
        title: "Dynamic hedging: Managing vanilla and exotic options",
        author: "Taleb",
        year: 1997,
        note: "The practitioner classic on actually running an options book.",
        citation: "Taleb, N. N. (1997). Dynamic hedging: Managing vanilla and exotic options. Wiley.",
        why: [
          "The practitioner classic on actually running an options book.",
          "Deep on Greeks behavior, exotics, and real-world hedging risks.",
          "Covers what textbook models miss — gaps, liquidity, second-order effects.",
          "Author: Nassim Nicholas Taleb, former options trader and risk theorist (NYU Tandon).",
        ],
        cover: "taleb-dynamic-hedging.jpg",
        coverW: 904,
        coverH: 1360,
      },
      {
        title: "Paul Wilmott on quantitative finance",
        author: "Wilmott",
        year: 2006,
        note: "An intuition-rich tour of quantitative finance.",
        citation: "Wilmott, P. (2006). Paul Wilmott on quantitative finance (2nd ed.). Wiley.",
        why: [
          "An intuition-rich tour of quantitative finance.",
          "From a renowned practitioner-educator.",
          "Connects derivatives math to real market behavior.",
          "Author: Paul Wilmott, founder of the CQF and the Wilmott quant community.",
        ],
        cover: "wilmott-paul-wilmott-on-quantitative-finance.jpg",
        coverW: 1149,
        coverH: 1500,
      },
      {
        title: "The volatility surface: A practitioner’s guide",
        author: "Gatheral",
        year: 2006,
        note: "The definitive text on the implied-volatility surface.",
        citation: "Gatheral, J. (2006). The volatility surface: A practitioner’s guide. Wiley.",
        why: [
          "The definitive text on the implied-volatility surface.",
          "Standard reference for local and stochastic volatility models.",
          "Used to price and hedge exotic options.",
          "Author: Jim Gatheral, ex-head of equity-derivatives quant at Merrill Lynch; now Baruch College professor.",
        ],
        cover: "gatheral-the-volatility-surface.jpg",
        coverW: 1006,
        coverH: 1500,
      },
      {
        title: "Stochastic volatility modeling",
        author: "Bergomi",
        year: 2016,
        note: "The modern reference on local and stochastic volatility.",
        citation: "Bergomi, L. (2016). Stochastic volatility modeling. Chapman & Hall/CRC.",
        why: [
          "The modern reference on local and stochastic volatility.",
          "The advanced successor to Gatheral, used on derivatives desks.",
          "By a leading practitioner-quant (head of quant research, Société Générale).",
          "Author: Lorenzo Bergomi, head of quantitative research at Société Générale.",
        ],
        cover: "bergomi-stochastic-volatility-modeling.jpg",
        coverW: 856,
        coverH: 1360,
      },
      {
        title: "Monte Carlo methods in financial engineering",
        author: "Glasserman",
        year: 2003,
        note: "The authoritative reference on Monte Carlo methods in finance.",
        citation: "Glasserman, P. (2003). Monte Carlo methods in financial engineering. Springer.",
        why: [
          "The authoritative reference on Monte Carlo methods in finance.",
          "Covers simulation, variance reduction, and Greeks estimation.",
          "Underpins pricing of path-dependent, high-dimensional derivatives.",
          "Author: Paul Glasserman, professor at Columbia Business School.",
        ],
        cover: "glasserman-monte-carlo-methods-in-financial-engi.jpg",
        coverW: 827,
        coverH: 1253,
      },
    ],
  },
  {
    theme: "Portfolio Optimization & Asset Allocation",
    blurb: "From the mean–variance frontier to factor investing and robust allocation.",
    books: [
      {
        title: "Investments",
        author: "Bodie & Marcus",
        year: 2024,
        note: "The leading university textbook on investments.",
        citation: "Bodie, Z., Kane, A., & Marcus, A. J. (2024). Investments (13th ed.). McGraw-Hill.",
        why: [
          "The leading university textbook on investments.",
          "Covers risk-return, the CAPM, market efficiency, and asset classes.",
          "Foundational framework for all portfolio work.",
          "Authors: Zvi Bodie, Alex Kane, and Alan Marcus, leading finance academics.",
        ],
        cover: "bodie-investments.jpg",
        coverW: 500,
        coverH: 500,
      },
      {
        title: "Investment science",
        author: "Luenberger",
        year: 2013,
        note: "A clear, elegant introduction to investment mathematics.",
        citation: "Luenberger, D. G. (2013). Investment science (2nd ed.). Oxford University Press.",
        why: [
          "A clear, elegant introduction to investment mathematics.",
          "Spans cash flows, mean-variance theory, and derivatives.",
          "Ideal foundational bridge into quant portfolio work.",
          "Author: David Luenberger, professor of engineering and operations research at Stanford.",
        ],
        cover: "luenberger-investment-science.jpg",
        coverW: 400,
        coverH: 500,
      },
      {
        title: "Asset management: A systematic approach to factor investing",
        author: "Ang",
        year: 2014,
        note: "The definitive modern text on factor investing.",
        citation: "Ang, A. (2014). Asset management: A systematic approach to factor investing. Oxford University Press.",
        why: [
          "The definitive modern text on factor investing.",
          "Reframes allocation around factors, not asset-class labels.",
          "By Andrew Ang, who built BlackRock’s factor-investing business.",
          "Author: Andrew Ang, former Columbia professor; head of factor investing at BlackRock.",
        ],
        cover: "ang-asset-management.jpg",
        coverW: 308,
        coverH: 500,
      },
      {
        title: "Active portfolio management: A quantitative approach for producing superior returns and controlling risk",
        author: "Grinold & Kahn",
        year: 1999,
        note: "The definitive institutional text on quantitative active management.",
        citation: "Grinold, R. C., & Kahn, R. N. (1999). Active portfolio management: A quantitative approach for producing superior returns and controlling risk (2nd ed.). McGraw-Hill.",
        why: [
          "The definitive institutional text on quantitative active management.",
          "Introduced the information ratio and the Fundamental Law of Active Management.",
          "Foundational for factor investing and alpha research.",
          "Authors: Richard Grinold and Ronald Kahn, longtime heads of research at BARRA/BlackRock.",
        ],
        cover: "grinold-active-portfolio-management.jpg",
        coverW: 332,
        coverH: 500,
      },
      {
        title: "Introduction to risk parity and budgeting",
        author: "Roncalli",
        year: 2013,
        note: "The standard quant reference on risk-based allocation.",
        citation: "Roncalli, T. (2013). Introduction to risk parity and budgeting. Chapman & Hall/CRC.",
        why: [
          "The standard quant reference on risk-based allocation.",
          "Covers risk parity, risk budgeting, and equal-risk-contribution portfolios.",
          "The rigorous modern alternative to mean-variance.",
          "Author: Thierry Roncalli, head of quant research at Amundi and a risk-parity authority.",
        ],
        cover: "roncalli-introduction-to-risk-parity-and-budgeti.jpg",
        coverW: 262,
        coverH: 400,
      },
      {
        title: "Risk and asset allocation",
        author: "Meucci",
        year: 2005,
        note: "Advanced, unifying treatment of risk and asset allocation.",
        citation: "Meucci, A. (2005). Risk and asset allocation. Springer.",
        why: [
          "Advanced, unifying treatment of risk and asset allocation.",
          "Covers estimation, Bayesian methods, and robust optimization.",
          "Reflects how professionals build portfolios.",
          "Author: Attilio Meucci, buy-side quant and creator of the ARPM Bootcamp.",
        ],
        cover: "meucci-risk-and-asset-allocation.jpg",
        coverW: 312,
        coverH: 500,
      },
      {
        title: "Robust portfolio optimization and management",
        author: "Fabozzi & Focardi",
        year: 2007,
        note: "A focused treatment of robust portfolio construction.",
        citation: "Fabozzi, F. J., Kolm, P. N., Pachamanova, D. A., & Focardi, S. M. (2007). Robust portfolio optimization and management. Wiley.",
        why: [
          "A focused treatment of robust portfolio construction.",
          "Tackles estimation error and unstable covariance matrices.",
          "Moves beyond classical Markowitz toward real-world optimization.",
          "Authors: Frank Fabozzi with quant academics Petter Kolm (NYU), Dessislava Pachamanova, and Sergio Focardi.",
        ],
        cover: "fabozzi-robust-portfolio-optimization-and-manage.jpg",
        coverW: 311,
        coverH: 500,
      },
    ],
  },
  {
    theme: "Risk Management",
    blurb: "Measuring, stress-testing and surviving the tails.",
    books: [
      {
        title: "Risk management and financial institutions",
        author: "Hull",
        year: 2023,
        note: "A broad, accessible survey of financial risk management.",
        citation: "Hull, J. C. (2023). Risk management and financial institutions (6th ed.). Wiley.",
        why: [
          "A broad, accessible survey of financial risk management.",
          "Connects market, credit, and operational risk with regulation.",
          "Standard for risk professionals and the FRM exam.",
          "Author: John Hull, University of Toronto, Rotman School.",
        ],
        cover: "hull-risk-management-and-financial-institutions.jpg",
        coverW: 350,
        coverH: 499,
      },
      {
        title: "The essentials of risk management",
        author: "Crouhy & Mark",
        year: 2014,
        note: "A practitioner overview of enterprise risk management.",
        citation: "Crouhy, M., Galai, D., & Mark, R. (2014). The essentials of risk management (2nd ed.). McGraw-Hill.",
        why: [
          "A practitioner overview of enterprise risk management.",
          "Explains VaR, credit and operational risk, and governance.",
          "An ideal foundational read.",
          "Authors: Michel Crouhy (head of R&D, Natixis), Dan Galai (Hebrew University), and Robert Mark (former bank CRO).",
        ],
        cover: "crouhy-the-essentials-of-risk-management.jpg",
        coverW: 313,
        coverH: 500,
      },
      {
        title: "Quantitative risk management: Concepts, techniques and tools",
        author: "McNeil & Embrechts",
        year: 2015,
        note: "The rigorous graduate text on quantitative risk management.",
        citation: "McNeil, A. J., Frey, R., & Embrechts, P. (2015). Quantitative risk management: Concepts, techniques and tools (Rev. ed.). Princeton University Press.",
        why: [
          "The rigorous graduate text on quantitative risk management.",
          "Authoritative on extreme-value theory and copulas.",
          "Covers VaR, Expected Shortfall (CVaR), and coherent risk measures.",
          "Authors: Alexander McNeil, Rüdiger Frey, and Paul Embrechts (ETH Zurich), leaders in quantitative risk.",
        ],
        cover: "mcneil-quantitative-risk-management.jpg",
        coverW: 331,
        coverH: 500,
      },
      {
        title: "Copula methods in finance",
        author: "Cherubini & Vecchiato",
        year: 2004,
        note: "The first book-length treatment of copulas in finance.",
        citation: "Cherubini, U., Luciano, E., & Vecchiato, W. (2004). Copula methods in finance. Wiley.",
        why: [
          "The first book-length treatment of copulas in finance.",
          "Models dependence for pricing and risk aggregation.",
          "A focused, advanced complement to the copula chapters in McNeil.",
          "Authors: Umberto Cherubini and Elisa Luciano, Italian financial-mathematics academics.",
        ],
        cover: "cherubini-copula-methods-in-finance.jpg",
        coverW: 317,
        coverH: 475,
      },
      {
        title: "Market risk analysis",
        author: "Alexander",
        year: 2008,
        note: "A four-volume set: quantitative methods, financial econometrics, pricing & trading, and Value-at-Risk models.",
        citation: "Alexander, C. (2008). Market risk analysis (Vols. I–IV). Wiley.",
        why: [
          "A four-volume set: quantitative methods, financial econometrics, pricing & trading, and Value-at-Risk models.",
          "Prized for rigorous technical depth combined with unusual clarity.",
          "A complete market-risk reference shelf in one work.",
          "Author: Carol Alexander, University of Sussex professor; a leading market-risk academic and former editor of the Journal of Banking & Finance.",
        ],
        cover: "alexander-market-risk-analysis.jpg",
        coverW: 337,
        coverH: 500,
      },
    ],
  },
  {
    theme: "Market Microstructure & Execution",
    blurb: "How orders become prices — liquidity, market impact and execution.",
    books: [
      {
        title: "Trading and exchanges: Market microstructure for practitioners",
        author: "Harris",
        year: 2003,
        note: "The most accessible guide to how markets actually work.",
        citation: "Harris, L. (2003). Trading and exchanges: Market microstructure for practitioners. Oxford University Press.",
        why: [
          "The most accessible guide to how markets actually work.",
          "Explains order types, liquidity, and trading mechanics.",
          "The ideal first book on microstructure.",
          "Author: Larry Harris, USC Marshall professor and former Chief Economist of the SEC.",
        ],
        cover: "harris-trading-and-exchanges.jpg",
        coverW: 364,
        coverH: 500,
      },
      {
        title: "Market microstructure theory",
        author: "O’Hara",
        year: 1995,
        note: "The classic theoretical foundation of market microstructure.",
        citation: "O’Hara, M. (1995). Market microstructure theory. Blackwell.",
        why: [
          "The classic theoretical foundation of market microstructure.",
          "Formalizes how information and inventory shape prices and spreads.",
          "A standard academic reference.",
          "Author: Maureen O’Hara, Cornell professor and a founder of market-microstructure theory.",
        ],
        cover: "o-hara-market-microstructure-theory.jpg",
        coverW: 340,
        coverH: 475,
      },
      {
        title: "Market liquidity: Theory, evidence, and policy",
        author: "Foucault & Röell",
        year: 2024,
        note: "A modern graduate synthesis of market-liquidity research.",
        citation: "Foucault, T., Pagano, M., & Röell, A. (2024). Market liquidity: Theory, evidence, and policy (2nd ed.). Oxford University Press.",
        why: [
          "A modern graduate synthesis of market-liquidity research.",
          "Surveys the theory, evidence, and policy of liquidity.",
          "Rigorous treatment of how markets price liquidity.",
          "Authors: Thierry Foucault (HEC Paris), Marco Pagano (Naples), and Ailsa Röell (Columbia).",
        ],
        cover: "foucault-market-liquidity.jpg",
        coverW: 282,
        coverH: 500,
      },
    ],
  },
  {
    theme: "Algorithmic Trading & Machine Learning",
    blurb: "Systematic strategies and machine learning applied to live markets.",
    books: [
      {
        title: "Quantitative trading: How to build your own algorithmic trading business",
        author: "Chan",
        year: 2021,
        note: "An accessible, hands-on intro to building a retail quant trading business.",
        citation: "Chan, E. P. (2021). Quantitative trading: How to build your own algorithmic trading business (2nd ed.). Wiley.",
        why: [
          "An accessible, hands-on intro to building a retail quant trading business.",
          "Demystifies backtesting and strategy evaluation.",
          "Covers the practical realities of going live.",
          "Author: Ernest Chan, former quant at Morgan Stanley and Credit Suisse; founder of QTS Capital.",
        ],
        cover: "chan-quantitative-trading.jpg",
        coverW: 375,
        coverH: 500,
      },
      {
        title: "Algorithmic trading: Winning strategies and their rationale",
        author: "Chan",
        year: 2013,
        note: "A more advanced sequel with concrete strategies.",
        citation: "Chan, E. P. (2013). Algorithmic trading: Winning strategies and their rationale. Wiley.",
        why: [
          "A more advanced sequel with concrete strategies.",
          "Covers mean-reversion and momentum.",
          "Includes the statistical tests to validate them.",
          "Author: Ernest Chan (QTS Capital; ex-Morgan Stanley).",
        ],
      },
      {
        title: "Systematic trading: A unique new method for designing trading and investing systems",
        author: "Carver",
        year: 2015,
        note: "A framework for designing systematic trading systems.",
        citation: "Carver, R. (2015). Systematic trading: A unique new method for designing trading and investing systems. Harriman House.",
        why: [
          "A framework for designing systematic trading systems.",
          "Strong on position sizing and diversification.",
          "Focused on avoiding overfitting.",
          "Author: Robert Carver, former systematic portfolio manager at AHL / Man Group.",
        ],
        cover: "carver-systematic-trading.jpg",
        coverW: 333,
        coverH: 500,
      },
      {
        title: "Algorithmic trading methods: Applications using advanced statistics, optimization, and machine learning techniques",
        author: "Kissell",
        year: 2021,
        note: "The leading applied reference on trading costs and execution.",
        citation: "Kissell, R. (2021). Algorithmic trading methods: Applications using advanced statistics, optimization, and machine learning techniques (2nd ed.). Academic Press.",
        why: [
          "The leading applied reference on trading costs and execution.",
          "Covers market-impact modeling and TWAP/VWAP algorithms.",
          "2nd edition adds advanced statistics, optimization, and machine learning.",
          "Author: Robert Kissell, a transaction-cost-analysis authority with senior execution-research roles on Wall Street.",
        ],
      },
      {
        title: "Python for finance: Mastering data-driven finance",
        author: "Hilpisch",
        year: 2018,
        note: "The standard reference for doing finance with Python.",
        citation: "Hilpisch, Y. J. (2018). Python for finance: Mastering data-driven finance (2nd ed.). O’Reilly Media.",
        why: [
          "The standard reference for doing finance with Python.",
          "Covers data handling and derivatives analytics.",
          "Includes Monte Carlo simulation.",
          "Author: Yves Hilpisch, founder of The Python Quants and the Certificate in Python for Finance.",
        ],
        cover: "hilpisch-python-for-finance.jpg",
        coverW: 381,
        coverH: 500,
      },
      {
        title: "Python for algorithmic trading: From idea to cloud deployment",
        author: "Hilpisch",
        year: 2020,
        note: "An end-to-end guide to automated trading in Python.",
        citation: "Hilpisch, Y. J. (2020). Python for algorithmic trading: From idea to cloud deployment. O’Reilly Media.",
        why: [
          "An end-to-end guide to automated trading in Python.",
          "Covers backtesting and broker APIs.",
          "Includes cloud deployment of live strategies.",
          "Author: Yves Hilpisch (The Python Quants).",
        ],
      },
      {
        title: "Python for algorithmic trading cookbook",
        author: "Strimpel",
        year: 2024,
        note: "A modern cookbook for the algo-trading workflow in Python.",
        citation: "Strimpel, J. (2024). Python for algorithmic trading cookbook. Packt Publishing.",
        why: [
          "A modern cookbook for the algo-trading workflow in Python.",
          "Up-to-date recipes for data, signals, and backtesting.",
          "Covers execution.",
          "Author: Jason Strimpel, founder of PyQuant News and a quant-finance practitioner.",
        ],
      },
      {
        title: "Machine learning for algorithmic trading",
        author: "Jansen",
        year: 2020,
        note: "A comprehensive, code-rich guide to ML for trading.",
        citation: "Jansen, S. (2020). Machine learning for algorithmic trading (2nd ed.). Packt Publishing. (3rd ed. release: 10/2026)",
        why: [
          "A comprehensive, code-rich guide to ML for trading.",
          "800+ pages spanning data sourcing to deployment.",
          "Full ML workflow in Python.",
          "Author: Stefan Jansen, founder of Applied AI; former fund manager and data scientist.",
        ],
        cover: "jansen-machine-learning-for-algorithmic-trading.jpg",
        coverW: 406,
        coverH: 500,
      },
      {
        title: "Machine learning in finance: From theory to practice",
        author: "Dixon & Bilokon",
        year: 2020,
        note: "The rigorous, comprehensive ML-in-finance textbook.",
        citation: "Dixon, M. F., Halperin, I., & Bilokon, P. (2020). Machine learning in finance: From theory to practice. Springer.",
        why: [
          "The rigorous, comprehensive ML-in-finance textbook.",
          "Covers supervised learning, deep learning, and reinforcement learning.",
          "Roughly half the book is devoted to reinforcement learning.",
          "Authors: Matthew Dixon (Illinois Tech), Igor Halperin (ex-Fidelity/JPMorgan quant), and Paul Bilokon (ex-Deutsche Bank; Imperial College; Thalesians founder).",
        ],
        cover: "dixon-machine-learning-in-finance.jpg",
        coverW: 332,
        coverH: 500,
      },
      {
        title: "Advances in financial machine learning",
        author: "López de Prado",
        year: 2018,
        note: "A landmark text on rigorous ML in finance.",
        citation: "López de Prado, M. (2018). Advances in financial machine learning. Wiley.",
        why: [
          "A landmark text on rigorous ML in finance.",
          "Exposes common backtesting pitfalls.",
          "Introduces meta-labeling and purged cross-validation.",
          "Author: Marcos López de Prado, ex-AQR/Guggenheim quant; now at ADIA Lab and Cornell.",
        ],
        cover: "l-pez-de-prado-advances-in-financial-machine-lea.jpg",
        coverW: 500,
        coverH: 500,
      },
      {
        title: "Machine learning for asset managers",
        author: "López de Prado",
        year: 2020,
        note: "A concise companion to Advances in Financial ML, focused on investment.",
        citation: "López de Prado, M. (2020). Machine learning for asset managers. Cambridge University Press.",
        why: [
          "A concise companion to Advances in Financial ML, focused on investment.",
          "Covers denoising covariance matrices, clustering, and feature importance.",
          "Emphasizes that ML complements, not replaces, classical methods.",
          "Author: Marcos López de Prado (ADIA Lab; Cornell).",
        ],
      },
    ],
  },
];

export const PAPERS: Paper[] = [
  { year: 1952, authors: "Harry Markowitz", title: "Portfolio Selection", journal: "The Journal of Finance", note: "Mean–variance optimisation — the birth of modern portfolio theory." },
  { year: 1958, authors: "James Tobin", title: "Liquidity Preference as Behavior Towards Risk", journal: "Review of Economic Studies", note: "The two-fund separation theorem." },
  { year: 1964, authors: "William F. Sharpe", title: "Capital Asset Prices", journal: "The Journal of Finance", note: "The CAPM — risk priced by a single market beta." },
  { year: 1970, authors: "Eugene F. Fama", title: "Efficient Capital Markets: A Review of Theory and Empirical Work", journal: "The Journal of Finance", note: "The efficient-market hypothesis, formalised." },
  { year: 1973, authors: "Fischer Black & Myron Scholes", title: "The Pricing of Options and Corporate Liabilities", journal: "Journal of Political Economy", note: "The option-pricing formula — replication and no-arbitrage.", article: "black-scholes-from-first-principles" },
  { year: 1973, authors: "Robert C. Merton", title: "Theory of Rational Option Pricing", journal: "Bell Journal of Economics", note: "Extends and generalises Black–Scholes." },
  { year: 1976, authors: "Stephen A. Ross", title: "The Arbitrage Theory of Capital Asset Pricing", journal: "Journal of Economic Theory", note: "APT — multi-factor returns from no-arbitrage." },
  { year: 1979, authors: "Cox, Ross & Rubinstein", title: "Option Pricing: A Simplified Approach", journal: "Journal of Financial Economics", note: "The binomial tree — pricing options by backward induction." },
  { year: 1982, authors: "Robert F. Engle", title: "Autoregressive Conditional Heteroscedasticity", journal: "Econometrica", note: "ARCH — modelling time-varying volatility (a Nobel idea)." },
  { year: 1985, authors: "Albert S. Kyle", title: "Continuous Auctions and Insider Trading", journal: "Econometrica", note: "The foundational model of market microstructure and price impact." },
  { year: 1986, authors: "Tim Bollerslev", title: "Generalized Autoregressive Conditional Heteroscedasticity", journal: "Journal of Econometrics", note: "GARCH — the workhorse volatility model.", article: "evt-t-copula-var" },
  { year: 1992, authors: "Fischer Black & Robert Litterman", title: "Global Portfolio Optimization", journal: "Financial Analysts Journal", note: "Blending market equilibrium with investor views — Black–Litterman." },
  { year: 1993, authors: "Eugene F. Fama & Kenneth R. French", title: "Common Risk Factors in the Returns on Stocks and Bonds", journal: "Journal of Financial Economics", note: "The three-factor model — size and value beyond the market." },
  { year: 1993, authors: "Narasimhan Jegadeesh & Sheridan Titman", title: "Returns to Buying Winners and Selling Losers", journal: "The Journal of Finance", note: "Momentum — the most documented anomaly in finance.", article: "cross-sectional-momentum" },
  { year: 1993, authors: "Steven L. Heston", title: "A Closed-Form Solution for Options with Stochastic Volatility", journal: "Review of Financial Studies", note: "The Heston model — volatility that is itself random." },
  { year: 1997, authors: "Mark M. Carhart", title: "On Persistence in Mutual Fund Performance", journal: "The Journal of Finance", note: "Adds momentum as a fourth pricing factor." },
  { year: 2000, authors: "Alexander J. McNeil & Rüdiger Frey", title: "Estimation of Tail-Related Risk Measures for Heteroscedastic Financial Time Series", journal: "Journal of Empirical Finance", note: "GARCH + Extreme Value Theory — conditional tail risk.", article: "evt-t-copula-var" },
  { year: 2001, authors: "Robert Almgren & Neil Chriss", title: "Optimal Execution of Portfolio Transactions", journal: "Journal of Risk", note: "The cost–risk frontier of trading — foundational for execution." },
  { year: 2004, authors: "Olivier Ledoit & Michael Wolf", title: "Honey, I Shrunk the Sample Covariance Matrix", journal: "Journal of Portfolio Management", note: "Shrinkage — a well-conditioned covariance that survives out-of-sample.", article: "ledoit-wolf-shrinkage" },
  { year: 2015, authors: "Eugene F. Fama & Kenneth R. French", title: "A Five-Factor Asset Pricing Model", journal: "Journal of Financial Economics", note: "Adds profitability and investment to the factor zoo." },
  { year: 2016, authors: "Marcos López de Prado", title: "Building Diversified Portfolios that Outperform Out of Sample", journal: "Journal of Portfolio Management", note: "Hierarchical Risk Parity — allocation without inverting a covariance matrix.", article: "hierarchical-risk-parity" },
];

export const BOOK_COUNT = BOOK_GROUPS.reduce((n, g) => n + g.books.length, 0);
export const PAPER_COUNT = PAPERS.length;
