/* ============================================================================
   Literature — Milestone 3. The canon: the books and the landmark papers that
   built quantitative finance over the last ~75 years. Curated, accurately cited.
   Each book carries a short tagline (`note`) and 2–3 "why it matters" bullets
   (`why`) surfaced in the expandable card. Drop a cover image at
   public/covers/<cover> and set `cover` to show real artwork; otherwise the card
   renders a styled typographic cover. Papers that map onto our research articles
   carry an `article` slug so the library cross-links into the case studies.
   ========================================================================== */

export interface Book {
  title: string;
  author: string;
  year: number;
  note: string;       // one-line tagline (teaser / first "why" point)
  why: string[];      // 2–3 bullets revealed in "Why it matters"
  cover?: string;     // optional /covers/<file>; falls back to a typographic cover
  coverW?: number;    // intrinsic cover width  (px) — reserves true aspect ratio
  coverH?: number;    // intrinsic cover height (px)
  citation?: string;  // full APA citation, shown in the hover detail layer
}

export interface BookGroup {
  theme: string;
  blurb: string;
  books: Book[];
}

export interface Paper {
  year: number;
  authors: string;
  title: string;
  journal: string;
  note: string;
  article?: string; // slug in /research/<article>
  category?: string; // one of the BOOK_GROUPS themes — groups papers like the books
  why?: string[]; // importance bullets, shown in the dropdown
  authorNote?: string; // a few facts on the author(s), shown in the dropdown
  logo?: string; // journal/publisher logo — file in /public/logos/papers/<logo>
  ref?: string; // citation detail after the journal, e.g. "36(4), 394–419"
}

/* --------------------------------------------------------------- books -- */

export const BOOK_GROUPS: BookGroup[] = [
  {
    theme: "Foundations",
    blurb: "The mathematics, probability and stochastic calculus everything else is built on.",
    books: [
      {
        title: "Financial calculus: An introduction to derivative pricing",
        author: "Baxter & Rennie",
        year: 1996,
        note: "A famous textbook and classic guide in quantitative finance.",
        citation: "Baxter, M., & Rennie, A. (1996). Financial calculus: An introduction to derivative pricing. Cambridge University Press.",
        why: [
          "A famous textbook and classic guide in quantitative finance.",
          "Explains the complex math used to find fair prices for financial derivatives.",
          "Bridges high-level mathematical theory and practical use on trading desks.",
          "Authors: Martin Baxter and Andrew Rennie, industry derivatives quants.",
        ],
        cover: "baxter-financial-calculus.jpg",
        coverW: 855,
        coverH: 1360,
      },
      {
        title: "The concepts and practice of mathematical finance (2nd ed.)",
        author: "Joshi",
        year: 2008,
        note: "A highly respected guide to quantitative finance.",
        citation: "Joshi, M. S. (2008). The concepts and practice of mathematical finance. Cambridge University Press.",
        why: [
          "A highly respected guide to quantitative finance.",
          "Bridges the gap between complex mathematical theory and practical trading-floor applications.",
          "Strong emphasis on how models are actually implemented.",
          "Author: Mark Joshi, former bank quant (RBS) and professor at the University of Melbourne.",
        ],
        cover: "joshi-the-concepts-and-practice-of-mathematical-.jpg",
        coverW: 897,
        coverH: 1360,
      },
      {
        title: "Stochastic calculus for finance II: Continuous-time models",
        author: "Shreve",
        year: 2004,
        note: "Highly popular text from Carnegie Mellon’s renowned computational finance master’s program.",
        citation: "Shreve, S. E. (2004). Stochastic calculus for finance II: Continuous-time models. Springer.",
        why: [
          "Highly popular text from Carnegie Mellon’s renowned computational finance master’s program.",
          "A core guide for quants and financial engineers.",
          "Models stock prices, interest rates, and options under randomness over time.",
          "Author: Steven Shreve, Carnegie Mellon professor and co-founder of its computational-finance master’s.",
        ],
        cover: "shreve-stochastic-calculus-for-finance-ii.jpg",
        coverW: 827,
        coverH: 1245,
      },
      {
        title: "Arbitrage theory in continuous time (4th ed.)",
        author: "Björk",
        year: 2020,
        note: "The standard graduate text on arbitrage pricing in continuous time.",
        citation: "Björk, T. (2020). Arbitrage theory in continuous time. Oxford University Press.",
        why: [
          "The standard graduate text on arbitrage pricing in continuous time.",
          "Develops martingale and measure-change methods rigorously yet readably.",
          "Bridges pure stochastic calculus and derivative pricing.",
          "Author: Tomas Björk, professor at the Stockholm School of Economics.",
        ],
        cover: "bj-rk-arbitrage-theory-in-continuous-time.jpg",
        coverW: 856,
        coverH: 1360,
      },
      {
        title: "Brownian motion and stochastic calculus (2nd ed.)",
        author: "Karatzas & Shreve",
        year: 1991,
        note: "The definitive mathematical reference on Brownian motion and stochastic calculus.",
        citation: "Karatzas, I., & Shreve, S. E. (1991). Brownian motion and stochastic calculus. Springer.",
        why: [
          "The definitive mathematical reference on Brownian motion and stochastic calculus.",
          "Aimed at advanced readers.",
          "Supplies the rigorous foundations under every continuous-time pricing model.",
          "Authors: Ioannis Karatzas (Columbia) and Steven Shreve (Carnegie Mellon), leading probabilists.",
        ],
        cover: "karatzas-brownian-motion-and-stochastic-calculus.jpg",
        coverW: 827,
        coverH: 1254,
      },
      {
        title: "Statistical inference (2nd ed.)",
        author: "Casella & Berger",
        year: 2002,
        note: "The standard graduate text on mathematical statistics and inference.",
        citation: "Casella, G., & Berger, R. L. (2002). Statistical inference. Duxbury.",
        why: [
          "The standard graduate text on mathematical statistics and inference.",
          "Rigorous foundation in estimation, hypothesis testing, and likelihood.",
          "The statistics backbone behind econometrics and model validation.",
          "Authors: George Casella and Roger Berger, eminent academic statisticians.",
        ],
        cover: "casella-statistical-inference.jpg",
        coverW: 350,
        coverH: 514,
      },
      {
        title: "Analysis of financial time series (3rd ed.)",
        author: "Tsay",
        year: 2010,
        note: "The standard applied text on financial time series.",
        citation: "Tsay, R. S. (2010). Analysis of financial time series. Wiley.",
        why: [
          "The standard applied text on financial time series.",
          "Covers volatility modeling (GARCH), return dynamics, and multivariate methods.",
          "A staple of empirical quant research.",
          "Author: Ruey Tsay, professor of econometrics and statistics at Chicago Booth.",
        ],
        cover: "tsay-analysis-of-financial-time-series.jpg",
        coverW: 978,
        coverH: 1500,
      },
      {
        title: "Time series analysis",
        author: "Hamilton",
        year: 1994,
        note: "The authoritative reference on time-series econometrics.",
        citation: "Hamilton, J. D. (1994). Time series analysis. Princeton University Press.",
        why: [
          "The authoritative reference on time-series econometrics.",
          "Go-to source for ARMA, state-space, VAR, and regime-switching models.",
          "Dense and comprehensive.",
          "Author: James Hamilton, professor at UC San Diego; a leading time-series econometrician.",
        ],
        cover: "hamilton-time-series-analysis.jpg",
        coverW: 956,
        coverH: 1500,
      },
      {
        title: "A first course in probability (10th ed.)",
        author: "Ross",
        year: 2019,
        note: "A classic first course in probability used worldwide.",
        citation: "Ross, S. M. (2019). A first course in probability. Pearson.",
        why: [
          "A classic first course in probability used worldwide.",
          "Builds core intuition for randomness, distributions, and expectation.",
          "Foundational for every quantitative discipline.",
          "Author: Sheldon Ross, professor at USC and a prolific applied-probability author.",
        ],
        cover: "ross-a-first-course-in-probability.jpg",
        coverW: 370,
        coverH: 474,
      },
      {
        title: "Introduction to probability (2nd ed.)",
        author: "Blitzstein & Hwang",
        year: 2019,
        note: "Modern, intuition-first text from Harvard’s popular Stat 110 course.",
        citation: "Blitzstein, J. K., & Hwang, J. (2019). Introduction to probability. Chapman & Hall/CRC.",
        why: [
          "Modern, intuition-first text from Harvard’s popular Stat 110 course.",
          "Makes conditioning, distributions, and stochastic thinking understandable.",
          "Widely praised for clarity.",
          "Authors: Joe Blitzstein (Harvard, Stat 110) and Jessica Hwang (Stanford).",
        ],
        cover: "blitzstein-introduction-to-probability.jpg",
        coverW: 949,
        coverH: 1400,
      },
      {
        title: "The econometrics of financial markets",
        author: "Campbell & MacKinlay",
        year: 1997,
        note: "The foundational graduate text in financial econometrics.",
        citation: "Campbell, J. Y., Lo, A. W., & MacKinlay, A. C. (1997). The econometrics of financial markets. Princeton University Press.",
        why: [
          "The foundational graduate text in financial econometrics.",
          "Links asset-pricing theory to empirical testing.",
          "Standard reference for factor models and market-efficiency research.",
          "Authors: John Campbell (Harvard), Andrew Lo (MIT Sloan), and Craig MacKinlay (Wharton).",
        ],
        cover: "campbell-the-econometrics-of-financial-markets.jpg",
        coverW: 856,
        coverH: 1360,
      },
      {
        title: "Econometric analysis (8th ed.)",
        author: "Greene",
        year: 2018,
        note: "The encyclopedic graduate reference in econometrics.",
        citation: "Greene, W. H. (2018). Econometric analysis. Pearson.",
        why: [
          "The encyclopedic graduate reference in econometrics.",
          "One of the most-cited works in economics (90,000+ citations).",
          "Comprehensive across MLE, GMM, time series, panel, and limited-dependent models.",
          "Author: William Greene, professor at NYU Stern.",
        ],
        cover: "greene-econometric-analysis.jpg",
        coverW: 332,
        coverH: 400,
      },
    ],
  },
  {
    theme: "Fixed Income & Interest-Rate Modeling",
    blurb: "Bonds, the yield curve, and the models that price interest-rate risk.",
    books: [
      {
        title: "Fixed income analysis (5th ed.)",
        author: "Fabozzi",
        year: 2022,
        note: "The CFA-series standard on fixed income.",
        citation: "Fabozzi, F. J. (2022). Fixed income analysis. Wiley.",
        why: [
          "The CFA-series standard on fixed income.",
          "Covers bond math, term structure, credit, and securitized products.",
          "Institutional entry point to rates and credit analysis.",
          "Author: Frank Fabozzi, editor of the CFA fixed-income curriculum and the most prolific fixed-income author.",
        ],
        cover: "fabozzi-fixed-income-analysis.jpg",
        coverW: 637,
        coverH: 900,
      },
      {
        title: "Fixed income securities (4th ed.): Tools for today’s markets",
        author: "Tuckman & Serrat",
        year: 2022,
        note: "Modern, practitioner-oriented bestseller on fixed income.",
        citation: "Tuckman, B., & Serrat, A. (2022). Fixed income securities: Tools for today’s markets. Wiley.",
        why: [
          "Modern, practitioner-oriented bestseller on fixed income.",
          "Covers arbitrage pricing, duration/convexity, and curve construction.",
          "Reflects the tools used on rates desks today.",
          "Authors: Bruce Tuckman (NYU Stern; ex-Lehman/CME) and Angel Serrat (ex-JPMorgan PM).",
        ],
        cover: "tuckman-fixed-income-securities.jpg",
        coverW: 1014,
        coverH: 1500,
      },
      {
        title: "Fixed income securities: Valuation, risk, and risk management",
        author: "Veronesi",
        year: 2010,
        note: "Bridges bond fundamentals and quantitative rates modeling.",
        citation: "Veronesi, P. (2010). Fixed income securities: Valuation, risk, and risk management. Wiley.",
        why: [
          "Bridges bond fundamentals and quantitative rates modeling.",
          "Strong on valuation and risk management.",
          "Covers derivatives and structured products.",
          "Author: Pietro Veronesi, professor of finance at Chicago Booth.",
        ],
        cover: "veronesi-fixed-income-securities.jpg",
        coverW: 1000,
        coverH: 1427,
      },
      {
        title: "Bond pricing and yield curve modeling: A structural approach",
        author: "Rebonato",
        year: 2018,
        note: "A modern, authoritative treatment of the yield curve.",
        citation: "Rebonato, R. (2018). Bond pricing and yield curve modeling: A structural approach. Cambridge University Press.",
        why: [
          "A modern, authoritative treatment of the yield curve.",
          "A structural approach from a leading rates quant.",
          "Bridges heavy rates models and how curves are actually built.",
          "Author: Riccardo Rebonato, EDHEC professor; former head of rates/FX quant research at PIMCO and RBS.",
        ],
        cover: "rebonato-bond-pricing-and-yield-curve-modeling.jpg",
        coverW: 1003,
        coverH: 1500,
      },
      {
        title: "Interest rate models (2nd ed.)—Theory and practice: With smile, inflation and credit",
        author: "Brigo & Mercurio",
        year: 2006,
        note: "The definitive practitioner reference for interest-rate models.",
        citation: "Brigo, D., & Mercurio, F. (2006). Interest rate models—Theory and practice: With smile, inflation and credit. Springer.",
        why: [
          "The definitive practitioner reference for interest-rate models.",
          "Covers short-rate and market (LIBOR/HJM) models in depth.",
          "Detailed on calibration and smile-consistent pricing.",
          "Authors: Damiano Brigo (Imperial College) and Fabio Mercurio (head of quant analytics, Bloomberg).",
        ],
        cover: "brigo-interest-rate-models.jpg",
        coverW: 827,
        coverH: 1257,
      },
    ],
  },
  {
    theme: "Derivatives, Options & Volatility",
    blurb: "Options, futures and the volatility surface — how derivatives are priced and hedged.",
    books: [
      {
        title: "Options, futures, and other derivatives (11th ed.)",
        author: "Hull",
        year: 2021,
        note: "The most widely used derivatives textbook in the world.",
        citation: "Hull, J. C. (2021). Options, futures, and other derivatives. Pearson.",
        why: [
          "The most widely used derivatives textbook in the world.",
          "The common language of options, futures, swaps, and risk-neutral pricing.",
          "Standard for students and practitioners alike.",
          "Author: John Hull, professor at the University of Toronto’s Rotman School.",
        ],
        cover: "hull-options-futures-and-other-derivatives.jpg",
        coverW: 484,
        coverH: 613,
      },
      {
        title: "Option volatility and pricing (2nd ed.): Advanced trading strategies and techniques",
        author: "Natenberg",
        year: 2015,
        note: "The classic on options from a trader’s perspective.",
        citation: "Natenberg, S. (2015). Option volatility and pricing: Advanced trading strategies and techniques. McGraw-Hill.",
        why: [
          "The classic on options from a trader’s perspective.",
          "Builds intuition for the Greeks, volatility, and spreads.",
          "Light on heavy math; a perennial desk favorite.",
          "Author: Sheldon Natenberg, veteran options trader and educator (Chicago).",
        ],
        cover: "natenberg-option-volatility-and-pricing.jpg",
        coverW: 662,
        coverH: 1000,
      },
      {
        title: "Dynamic hedging: Managing vanilla and exotic options",
        author: "Taleb",
        year: 1997,
        note: "The practitioner classic on actually running an options book.",
        citation: "Taleb, N. N. (1997). Dynamic hedging: Managing vanilla and exotic options. Wiley.",
        why: [
          "The practitioner classic on actually running an options book.",
          "Deep on Greeks behavior, exotics, and real-world hedging risks.",
          "Covers what textbook models miss — gaps, liquidity, second-order effects.",
          "Author: Nassim Nicholas Taleb, former options trader and risk theorist (NYU Tandon).",
        ],
        cover: "taleb-dynamic-hedging.jpg",
        coverW: 904,
        coverH: 1360,
      },
      {
        title: "Paul Wilmott on quantitative finance (2nd ed.)",
        author: "Wilmott",
        year: 2006,
        note: "An intuition-rich tour of quantitative finance.",
        citation: "Wilmott, P. (2006). Paul Wilmott on quantitative finance. Wiley.",
        why: [
          "An intuition-rich tour of quantitative finance.",
          "From a renowned practitioner-educator.",
          "Connects derivatives math to real market behavior.",
          "Author: Paul Wilmott, founder of the CQF and the Wilmott quant community.",
        ],
        cover: "wilmott-paul-wilmott-on-quantitative-finance.jpg",
        coverW: 1149,
        coverH: 1500,
      },
      {
        title: "The volatility surface: A practitioner’s guide",
        author: "Gatheral",
        year: 2006,
        note: "The definitive text on the implied-volatility surface.",
        citation: "Gatheral, J. (2006). The volatility surface: A practitioner’s guide. Wiley.",
        why: [
          "The definitive text on the implied-volatility surface.",
          "Standard reference for local and stochastic volatility models.",
          "Used to price and hedge exotic options.",
          "Author: Jim Gatheral, ex-head of equity-derivatives quant at Merrill Lynch; now Baruch College professor.",
        ],
        cover: "gatheral-the-volatility-surface.jpg",
        coverW: 1006,
        coverH: 1500,
      },
      {
        title: "Stochastic volatility modeling",
        author: "Bergomi",
        year: 2016,
        note: "The modern reference on local and stochastic volatility.",
        citation: "Bergomi, L. (2016). Stochastic volatility modeling. Chapman & Hall/CRC.",
        why: [
          "The modern reference on local and stochastic volatility.",
          "The advanced successor to Gatheral, used on derivatives desks.",
          "By a leading practitioner-quant (head of quant research, Société Générale).",
          "Author: Lorenzo Bergomi, head of quantitative research at Société Générale.",
        ],
        cover: "bergomi-stochastic-volatility-modeling.jpg",
        coverW: 856,
        coverH: 1360,
      },
      {
        title: "Monte Carlo methods in financial engineering",
        author: "Glasserman",
        year: 2003,
        note: "The authoritative reference on Monte Carlo methods in finance.",
        citation: "Glasserman, P. (2003). Monte Carlo methods in financial engineering. Springer.",
        why: [
          "The authoritative reference on Monte Carlo methods in finance.",
          "Covers simulation, variance reduction, and Greeks estimation.",
          "Underpins pricing of path-dependent, high-dimensional derivatives.",
          "Author: Paul Glasserman, professor at Columbia Business School.",
        ],
        cover: "glasserman-monte-carlo-methods-in-financial-engi.jpg",
        coverW: 827,
        coverH: 1253,
      },
    ],
  },
  {
    theme: "Portfolio Optimization & Asset Allocation",
    blurb: "From the mean–variance frontier to factor investing and robust allocation.",
    books: [
      {
        title: "Investments (13th ed.)",
        author: "Bodie & Marcus",
        year: 2024,
        note: "The leading university textbook on investments.",
        citation: "Bodie, Z., Kane, A., & Marcus, A. J. (2024). Investments. McGraw-Hill.",
        why: [
          "The leading university textbook on investments.",
          "Covers risk-return, the CAPM, market efficiency, and asset classes.",
          "Foundational framework for all portfolio work.",
          "Authors: Zvi Bodie, Alex Kane, and Alan Marcus, leading finance academics.",
        ],
        cover: "bodie-investments.jpg",
        coverW: 1000,
        coverH: 1207,
      },
      {
        title: "Investment science (2nd ed.)",
        author: "Luenberger",
        year: 2013,
        note: "A clear, elegant introduction to investment mathematics.",
        citation: "Luenberger, D. G. (2013). Investment science. Oxford University Press.",
        why: [
          "A clear, elegant introduction to investment mathematics.",
          "Spans cash flows, mean-variance theory, and derivatives.",
          "Ideal foundational bridge into quant portfolio work.",
          "Author: David Luenberger, professor of engineering and operations research at Stanford.",
        ],
        cover: "luenberger-investment-science.jpg",
        coverW: 1216,
        coverH: 1500,
      },
      {
        title: "Asset management: A systematic approach to factor investing",
        author: "Ang",
        year: 2014,
        note: "The definitive modern text on factor investing.",
        citation: "Ang, A. (2014). Asset management: A systematic approach to factor investing. Oxford University Press.",
        why: [
          "The definitive modern text on factor investing.",
          "Reframes allocation around factors, not asset-class labels.",
          "By Andrew Ang, who built BlackRock’s factor-investing business.",
          "Author: Andrew Ang, former Columbia professor; head of factor investing at BlackRock.",
        ],
        cover: "ang-asset-management.jpg",
        coverW: 988,
        coverH: 1500,
      },
      {
        title: "Active portfolio management (2nd ed.): A quantitative approach for producing superior returns and controlling risk",
        author: "Grinold & Kahn",
        year: 1999,
        note: "The definitive institutional text on quantitative active management.",
        citation: "Grinold, R. C., & Kahn, R. N. (1999). Active portfolio management: A quantitative approach for producing superior returns and controlling risk. McGraw-Hill.",
        why: [
          "The definitive institutional text on quantitative active management.",
          "Introduced the information ratio and the Fundamental Law of Active Management.",
          "Foundational for factor investing and alpha research.",
          "Authors: Richard Grinold and Ronald Kahn, longtime heads of research at BARRA/BlackRock.",
        ],
        cover: "grinold-active-portfolio-management.jpg",
        coverW: 667,
        coverH: 1000,
      },
      {
        title: "Introduction to risk parity and budgeting",
        author: "Roncalli",
        year: 2013,
        note: "The standard quant reference on risk-based allocation.",
        citation: "Roncalli, T. (2013). Introduction to risk parity and budgeting. Chapman & Hall/CRC.",
        why: [
          "The standard quant reference on risk-based allocation.",
          "Covers risk parity, risk budgeting, and equal-risk-contribution portfolios.",
          "The rigorous modern alternative to mean-variance.",
          "Author: Thierry Roncalli, head of quant research at Amundi and a risk-parity authority.",
        ],
        cover: "roncalli-introduction-to-risk-parity-and-budgeti.jpg",
        coverW: 856,
        coverH: 1360,
      },
      {
        title: "Risk and asset allocation",
        author: "Meucci",
        year: 2005,
        note: "Advanced, unifying treatment of risk and asset allocation.",
        citation: "Meucci, A. (2005). Risk and asset allocation. Springer.",
        why: [
          "Advanced, unifying treatment of risk and asset allocation.",
          "Covers estimation, Bayesian methods, and robust optimization.",
          "Reflects how professionals build portfolios.",
          "Author: Attilio Meucci, buy-side quant and creator of the ARPM Bootcamp.",
        ],
        cover: "meucci-risk-and-asset-allocation.jpg",
        coverW: 827,
        coverH: 1247,
      },
      {
        title: "Robust portfolio optimization and management",
        author: "Fabozzi & Focardi",
        year: 2007,
        note: "A focused treatment of robust portfolio construction.",
        citation: "Fabozzi, F. J., Kolm, P. N., Pachamanova, D. A., & Focardi, S. M. (2007). Robust portfolio optimization and management. Wiley.",
        why: [
          "A focused treatment of robust portfolio construction.",
          "Tackles estimation error and unstable covariance matrices.",
          "Moves beyond classical Markowitz toward real-world optimization.",
          "Authors: Frank Fabozzi with quant academics Petter Kolm (NYU), Dessislava Pachamanova, and Sergio Focardi.",
        ],
        cover: "fabozzi-robust-portfolio-optimization-and-manage.jpg",
        coverW: 855,
        coverH: 1360,
      },
    ],
  },
  {
    theme: "Risk Management",
    blurb: "Measuring, stress-testing and surviving the tails.",
    books: [
      {
        title: "Risk management and financial institutions (6th ed.)",
        author: "Hull",
        year: 2023,
        note: "A broad, accessible survey of financial risk management.",
        citation: "Hull, J. C. (2023). Risk management and financial institutions. Wiley.",
        why: [
          "A broad, accessible survey of financial risk management.",
          "Connects market, credit, and operational risk with regulation.",
          "Standard for risk professionals and the FRM exam.",
          "Author: John Hull, University of Toronto, Rotman School.",
        ],
        cover: "hull-risk-management-and-financial-institutions.jpg",
        coverW: 1051,
        coverH: 1500,
      },
      {
        title: "The essentials of risk management (2nd ed.)",
        author: "Crouhy & Mark",
        year: 2014,
        note: "A practitioner overview of enterprise risk management.",
        citation: "Crouhy, M., Galai, D., & Mark, R. (2014). The essentials of risk management. McGraw-Hill.",
        why: [
          "A practitioner overview of enterprise risk management.",
          "Explains VaR, credit and operational risk, and governance.",
          "An ideal foundational read.",
          "Authors: Michel Crouhy (head of R&D, Natixis), Dan Galai (Hebrew University), and Robert Mark (former bank CRO).",
        ],
        cover: "crouhy-the-essentials-of-risk-management.jpg",
        coverW: 1000,
        coverH: 1500,
      },
      {
        title: "Quantitative risk management (Rev. ed.): Concepts, techniques and tools",
        author: "McNeil & Embrechts",
        year: 2015,
        note: "The rigorous graduate text on quantitative risk management.",
        citation: "McNeil, A. J., Frey, R., & Embrechts, P. (2015). Quantitative risk management: Concepts, techniques and tools. Princeton University Press.",
        why: [
          "The rigorous graduate text on quantitative risk management.",
          "Authoritative on extreme-value theory and copulas.",
          "Covers VaR, Expected Shortfall (CVaR), and coherent risk measures.",
          "Authors: Alexander McNeil, Rüdiger Frey, and Paul Embrechts (ETH Zurich), leaders in quantitative risk.",
        ],
        cover: "mcneil-quantitative-risk-management.jpg",
        coverW: 1212,
        coverH: 1500,
      },
      {
        title: "Copula methods in finance",
        author: "Cherubini & Vecchiato",
        year: 2004,
        note: "The first book-length treatment of copulas in finance.",
        citation: "Cherubini, U., Luciano, E., & Vecchiato, W. (2004). Copula methods in finance. Wiley.",
        why: [
          "The first book-length treatment of copulas in finance.",
          "Models dependence for pricing and risk aggregation.",
          "A focused, advanced complement to the copula chapters in McNeil.",
          "Authors: Umberto Cherubini and Elisa Luciano, Italian financial-mathematics academics.",
        ],
        cover: "cherubini-copula-methods-in-finance.jpg",
        coverW: 1002,
        coverH: 1500,
      },
      {
        title: "Market risk analysis",
        author: "Alexander",
        year: 2008,
        note: "A four-volume set: quantitative methods, financial econometrics, pricing & trading, and Value-at-Risk models.",
        citation: "Alexander, C. (2008). Market risk analysis (Vols. I–IV). Wiley.",
        why: [
          "A four-volume set: quantitative methods, financial econometrics, pricing & trading, and Value-at-Risk models.",
          "Prized for rigorous technical depth combined with unusual clarity.",
          "A complete market-risk reference shelf in one work.",
          "Author: Carol Alexander, University of Sussex professor; a leading market-risk academic and former editor of the Journal of Banking & Finance.",
        ],
        cover: "alexander-market-risk-analysis.jpg",
        coverW: 256,
        coverH: 369,
      },
    ],
  },
  {
    theme: "Market Microstructure & Execution",
    blurb: "How orders become prices — liquidity, market impact and execution.",
    books: [
      {
        title: "Trading and exchanges: Market microstructure for practitioners",
        author: "Harris",
        year: 2003,
        note: "The most accessible guide to how markets actually work.",
        citation: "Harris, L. (2003). Trading and exchanges: Market microstructure for practitioners. Oxford University Press.",
        why: [
          "The most accessible guide to how markets actually work.",
          "Explains order types, liquidity, and trading mechanics.",
          "The ideal first book on microstructure.",
          "Author: Larry Harris, USC Marshall professor and former Chief Economist of the SEC.",
        ],
        cover: "harris-trading-and-exchanges.jpg",
        coverW: 904,
        coverH: 1360,
      },
      {
        title: "Market microstructure theory",
        author: "O’Hara",
        year: 1995,
        note: "The classic theoretical foundation of market microstructure.",
        citation: "O’Hara, M. (1995). Market microstructure theory. Blackwell.",
        why: [
          "The classic theoretical foundation of market microstructure.",
          "Formalizes how information and inventory shape prices and spreads.",
          "A standard academic reference.",
          "Author: Maureen O’Hara, Cornell professor and a founder of market-microstructure theory.",
        ],
        cover: "o-hara-market-microstructure-theory.jpg",
        coverW: 907,
        coverH: 1360,
      },
      {
        title: "Market liquidity (2nd ed.): Theory, evidence, and policy",
        author: "Foucault & Röell",
        year: 2024,
        note: "A modern graduate synthesis of market-liquidity research.",
        citation: "Foucault, T., Pagano, M., & Röell, A. (2024). Market liquidity: Theory, evidence, and policy. Oxford University Press.",
        why: [
          "A modern graduate synthesis of market-liquidity research.",
          "Surveys the theory, evidence, and policy of liquidity.",
          "Rigorous treatment of how markets price liquidity.",
          "Authors: Thierry Foucault (HEC Paris), Marco Pagano (Naples), and Ailsa Röell (Columbia).",
        ],
        cover: "foucault-market-liquidity.jpg",
        coverW: 426,
        coverH: 648,
      },
    ],
  },
  {
    theme: "Algorithmic Trading & Machine Learning",
    blurb: "Systematic strategies and machine learning applied to live markets.",
    books: [
      {
        title: "Quantitative trading (2nd ed.): How to build your own algorithmic trading business",
        author: "Chan",
        year: 2021,
        note: "An accessible, hands-on intro to building a retail quant trading business.",
        citation: "Chan, E. P. (2021). Quantitative trading: How to build your own algorithmic trading business. Wiley.",
        why: [
          "An accessible, hands-on intro to building a retail quant trading business.",
          "Demystifies backtesting and strategy evaluation.",
          "Covers the practical realities of going live.",
          "Author: Ernest Chan, former quant at Morgan Stanley and Credit Suisse; founder of QTS Capital.",
        ],
        cover: "chan-quantitative-trading.jpg",
        coverW: 993,
        coverH: 1500,
      },
      {
        title: "Algorithmic trading: Winning strategies and their rationale",
        author: "Chan",
        year: 2013,
        note: "A more advanced sequel with concrete strategies.",
        citation: "Chan, E. P. (2013). Algorithmic trading: Winning strategies and their rationale. Wiley.",
        why: [
          "A more advanced sequel with concrete strategies.",
          "Covers mean-reversion and momentum.",
          "Includes the statistical tests to validate them.",
          "Author: Ernest Chan (QTS Capital; ex-Morgan Stanley).",
        ],
        cover: "chan-algorithmic-trading.jpg",
        coverW: 1014,
        coverH: 1500,
      },
      {
        title: "Systematic trading: A unique new method for designing trading and investing systems",
        author: "Carver",
        year: 2015,
        note: "A framework for designing systematic trading systems.",
        citation: "Carver, R. (2015). Systematic trading: A unique new method for designing trading and investing systems. Harriman House.",
        why: [
          "A framework for designing systematic trading systems.",
          "Strong on position sizing and diversification.",
          "Focused on avoiding overfitting.",
          "Author: Robert Carver, former systematic portfolio manager at AHL / Man Group.",
        ],
        cover: "carver-systematic-trading.jpg",
        coverW: 1000,
        coverH: 1500,
      },
      {
        title: "Algorithmic trading methods (2nd ed.): Applications using advanced statistics, optimization, and machine learning techniques",
        author: "Kissell",
        year: 2021,
        note: "The leading applied reference on trading costs and execution.",
        citation: "Kissell, R. (2021). Algorithmic trading methods: Applications using advanced statistics, optimization, and machine learning techniques. Academic Press.",
        why: [
          "The leading applied reference on trading costs and execution.",
          "Covers market-impact modeling and TWAP/VWAP algorithms.",
          "2nd edition adds advanced statistics, optimization, and machine learning.",
          "Author: Robert Kissell, a transaction-cost-analysis authority with senior execution-research roles on Wall Street.",
        ],
        cover: "kissell-algorithmic-trading-methods.jpg",
        coverW: 1103,
        coverH: 1360,
      },
      {
        title: "Python for finance (2nd ed.): Mastering data-driven finance",
        author: "Hilpisch",
        year: 2018,
        note: "The standard reference for doing finance with Python.",
        citation: "Hilpisch, Y. J. (2018). Python for finance: Mastering data-driven finance. O’Reilly Media.",
        why: [
          "The standard reference for doing finance with Python.",
          "Covers data handling and derivatives analytics.",
          "Includes Monte Carlo simulation.",
          "Author: Yves Hilpisch, founder of The Python Quants and the Certificate in Python for Finance.",
        ],
        cover: "hilpisch-python-for-finance.jpg",
        coverW: 1143,
        coverH: 1500,
      },
      {
        title: "Python for algorithmic trading: From idea to cloud deployment",
        author: "Hilpisch",
        year: 2020,
        note: "An end-to-end guide to automated trading in Python.",
        citation: "Hilpisch, Y. J. (2020). Python for algorithmic trading: From idea to cloud deployment. O’Reilly Media.",
        why: [
          "An end-to-end guide to automated trading in Python.",
          "Covers backtesting and broker APIs.",
          "Includes cloud deployment of live strategies.",
          "Author: Yves Hilpisch (The Python Quants).",
        ],
        cover: "hilpisch-python-for-algorithmic-trading.jpg",
        coverW: 1143,
        coverH: 1500,
      },
      {
        title: "Python for algorithmic trading cookbook",
        author: "Strimpel",
        year: 2024,
        note: "A modern cookbook for the algo-trading workflow in Python.",
        citation: "Strimpel, J. (2024). Python for algorithmic trading cookbook. Packt Publishing.",
        why: [
          "A modern cookbook for the algo-trading workflow in Python.",
          "Up-to-date recipes for data, signals, and backtesting.",
          "Covers execution.",
          "Author: Jason Strimpel, founder of PyQuant News and a quant-finance practitioner.",
        ],
        cover: "strimpel-python-for-algorithmic-trading-cookbook.jpg",
        coverW: 1216,
        coverH: 1500,
      },
      {
        title: "Machine learning for algorithmic trading (2nd ed.)",
        author: "Jansen",
        year: 2020,
        note: "A comprehensive, code-rich guide to ML for trading.",
        citation: "Jansen, S. (2020). Machine learning for algorithmic trading. Packt Publishing. (3rd ed. release: 10/2026)",
        why: [
          "A comprehensive, code-rich guide to ML for trading.",
          "800+ pages spanning data sourcing to deployment.",
          "Full ML workflow in Python.",
          "Author: Stefan Jansen, founder of Applied AI; former fund manager and data scientist.",
        ],
        cover: "jansen-machine-learning-for-algorithmic-trading.jpg",
        coverW: 1047,
        coverH: 1360,
      },
      {
        title: "Machine learning in finance: From theory to practice",
        author: "Dixon & Bilokon",
        year: 2020,
        note: "The rigorous, comprehensive ML-in-finance textbook.",
        citation: "Dixon, M. F., Halperin, I., & Bilokon, P. (2020). Machine learning in finance: From theory to practice. Springer.",
        why: [
          "The rigorous, comprehensive ML-in-finance textbook.",
          "Covers supervised learning, deep learning, and reinforcement learning.",
          "Roughly half the book is devoted to reinforcement learning.",
          "Authors: Matthew Dixon (Illinois Tech), Igor Halperin (ex-Fidelity/JPMorgan quant), and Paul Bilokon (ex-Deutsche Bank; Imperial College; Thalesians founder).",
        ],
        cover: "dixon-machine-learning-in-finance.jpg",
        coverW: 827,
        coverH: 1245,
      },
      {
        title: "Advances in financial machine learning",
        author: "López de Prado",
        year: 2018,
        note: "A landmark text on rigorous ML in finance.",
        citation: "López de Prado, M. (2018). Advances in financial machine learning. Wiley.",
        why: [
          "A landmark text on rigorous ML in finance.",
          "Exposes common backtesting pitfalls.",
          "Introduces meta-labeling and purged cross-validation.",
          "Author: Marcos López de Prado, ex-AQR/Guggenheim quant; now at ADIA Lab and Cornell.",
        ],
        cover: "l-pez-de-prado-advances-in-financial-machine-lea.jpg",
        coverW: 256,
        coverH: 387,
      },
      {
        title: "Machine learning for asset managers",
        author: "López de Prado",
        year: 2020,
        note: "A concise companion to Advances in Financial ML, focused on investment.",
        citation: "López de Prado, M. (2020). Machine learning for asset managers. Cambridge University Press.",
        why: [
          "A concise companion to Advances in Financial ML, focused on investment.",
          "Covers denoising covariance matrices, clustering, and feature importance.",
          "Emphasizes that ML complements, not replaces, classical methods.",
          "Author: Marcos López de Prado (ADIA Lab; Cornell).",
        ],
        cover: "lopez-de-prado-machine-learning-for-asset-managers.jpg",
        coverW: 1000,
        coverH: 1500,
      },
    ],
  },
];

export const PAPERS: Paper[] = [
  { year: 1952, authors: "Harry Markowitz", title: "Portfolio Selection", journal: "The Journal of Finance", logo: "journal-of-finance.jpg", note: "Mean–variance optimisation — the birth of modern portfolio theory.", category: "Portfolio Optimization & Asset Allocation" },
  { year: 1958, authors: "James Tobin", title: "Liquidity Preference as Behavior Towards Risk", journal: "Review of Economic Studies", logo: "review-of-economic-studies.png", note: "The two-fund separation theorem.", category: "Portfolio Optimization & Asset Allocation" },
  { year: 1964, authors: "William F. Sharpe", title: "Capital Asset Prices", journal: "The Journal of Finance", logo: "journal-of-finance.jpg", note: "The CAPM — risk priced by a single market beta.", category: "Portfolio Optimization & Asset Allocation" },
  { year: 1970, authors: "Eugene F. Fama", title: "Efficient Capital Markets: A Review of Theory and Empirical Work", journal: "The Journal of Finance", logo: "journal-of-finance.jpg", note: "The efficient-market hypothesis, formalised.", category: "Foundations" },
  { year: 1973, authors: "Fischer Black & Myron Scholes", title: "The Pricing of Options and Corporate Liabilities", journal: "Journal of Political Economy", logo: "journal-of-political-economy.png", note: "The option-pricing formula — replication and no-arbitrage.", category: "Derivatives, Options & Volatility" },
  { year: 1973, authors: "Robert C. Merton", title: "Theory of Rational Option Pricing", journal: "Bell Journal of Economics", logo: "bell-journal-of-economics.svg", note: "Extends and generalises Black–Scholes.", category: "Derivatives, Options & Volatility" },
  { year: 1976, authors: "Stephen A. Ross", title: "The Arbitrage Theory of Capital Asset Pricing", journal: "Journal of Economic Theory", logo: "journal-of-economic-theory.png", note: "APT — multi-factor returns from no-arbitrage.", category: "Portfolio Optimization & Asset Allocation" },
  { year: 1979, authors: "Cox, Ross & Rubinstein", title: "Option Pricing: A Simplified Approach", journal: "Journal of Financial Economics", logo: "journal-of-financial-economics.webp", note: "The binomial tree — pricing options by backward induction.", category: "Derivatives, Options & Volatility" },
  { year: 1982, authors: "Robert F. Engle", title: "Autoregressive Conditional Heteroscedasticity", journal: "Econometrica", logo: "econometrica.png", note: "ARCH — modelling time-varying volatility (a Nobel idea).", category: "Risk Management" },
  { year: 1985, authors: "Albert S. Kyle", title: "Continuous Auctions and Insider Trading", journal: "Econometrica", logo: "econometrica.png", note: "The foundational model of market microstructure and price impact.", category: "Market Microstructure & Execution" },
  { year: 1986, authors: "Tim Bollerslev", title: "Generalized Autoregressive Conditional Heteroscedasticity", journal: "Journal of Econometrics", logo: "journal-of-econometrics.png", note: "GARCH — the workhorse volatility model.", category: "Risk Management" },
  { year: 1992, authors: "Fischer Black & Robert Litterman", title: "Global Portfolio Optimization", journal: "Financial Analysts Journal", logo: "financial-analysts-journal.png", note: "Blending market equilibrium with investor views — Black–Litterman.", category: "Portfolio Optimization & Asset Allocation" },
  { year: 1993, authors: "Eugene F. Fama & Kenneth R. French", title: "Common Risk Factors in the Returns on Stocks and Bonds", journal: "Journal of Financial Economics", logo: "journal-of-financial-economics.webp", note: "The three-factor model — size and value beyond the market.", category: "Portfolio Optimization & Asset Allocation" },
  { year: 1993, authors: "Narasimhan Jegadeesh & Sheridan Titman", title: "Returns to Buying Winners and Selling Losers", journal: "The Journal of Finance", logo: "journal-of-finance.jpg", note: "Momentum — the most documented anomaly in finance.", category: "Algorithmic Trading & Machine Learning" },
  { year: 1993, authors: "Steven L. Heston", title: "A Closed-Form Solution for Options with Stochastic Volatility", journal: "Review of Financial Studies", logo: "review-of-financial-studies.png", note: "The Heston model — volatility that is itself random.", category: "Derivatives, Options & Volatility" },
  { year: 1997, authors: "Mark M. Carhart", title: "On Persistence in Mutual Fund Performance", journal: "The Journal of Finance", logo: "journal-of-finance.jpg", note: "Adds momentum as a fourth pricing factor.", category: "Portfolio Optimization & Asset Allocation" },
  { year: 2000, authors: "Alexander J. McNeil & Rüdiger Frey", title: "Estimation of Tail-Related Risk Measures for Heteroscedastic Financial Time Series", journal: "Journal of Empirical Finance", logo: "journal-of-empirical-finance.png", note: "GARCH + Extreme Value Theory — conditional tail risk.", category: "Risk Management" },
  { year: 2001, authors: "Robert Almgren & Neil Chriss", title: "Optimal Execution of Portfolio Transactions", journal: "Journal of Risk", logo: "journal-of-risk.svg", note: "The cost–risk frontier of trading — foundational for execution.", category: "Market Microstructure & Execution" },
  { year: 2004, authors: "Olivier Ledoit & Michael Wolf", title: "Honey, I Shrunk the Sample Covariance Matrix", journal: "Journal of Portfolio Management", logo: "journal-of-portfolio-management.png", note: "Shrinkage — a well-conditioned covariance that survives out-of-sample.", category: "Portfolio Optimization & Asset Allocation" },
  { year: 2015, authors: "Eugene F. Fama & Kenneth R. French", title: "A Five-Factor Asset Pricing Model", journal: "Journal of Financial Economics", logo: "journal-of-financial-economics.webp", note: "Adds profitability and investment to the factor zoo.", category: "Portfolio Optimization & Asset Allocation" },
  { year: 2016, authors: "Marcos López de Prado", title: "Building Diversified Portfolios that Outperform Out of Sample", journal: "Journal of Portfolio Management", logo: "journal-of-portfolio-management.png", note: "Hierarchical Risk Parity — allocation without inverting a covariance matrix.", category: "Algorithmic Trading & Machine Learning" },
];

/* --------------------------------------------------------- curated papers --
   The recommended-papers list shown in the Literature → Papers tab. Built up
   from client-supplied content (importance bullets + author facts + logos),
   grouped by the same categories as the books. */
export const PAPER_RECS: Paper[] = [
  {
    year: 1963,
    authors: "Mandelbrot, B.",
    title: "The variation of certain speculative prices",
    journal: "The Journal of Business",
    logo: "journal-of-business.svg",
    ref: "36(4), 394–419",
    note: "",
    category: "Foundations",
    why: [
      "Documented that speculative prices have heavy-tailed, non-Gaussian return distributions.",
      "Proposed stable (Paretian) distributions and the possibility of infinite variance in price changes.",
      "Foundational challenge to the normality assumption underlying later option models.",
    ],
    authorNote: "Benoit Mandelbrot, IBM Fellow and mathematician, father of fractal geometry.",
  },
  {
    year: 1982,
    authors: "Engle, R. F.",
    title: "Autoregressive conditional heteroscedasticity with estimates of the variance of United Kingdom inflation",
    journal: "Econometrica",
    logo: "econometrica.png",
    ref: "50(4), 987–1007",
    note: "",
    category: "Foundations",
    why: [
      "Introduced the ARCH model, letting variance evolve conditional on past shocks.",
      "Gave econometrics its first rigorous framework for volatility clustering.",
      "Work recognized by the 2003 Nobel Memorial Prize in Economics.",
    ],
    authorNote: "Robert Engle, professor at NYU Stern; 2003 Nobel laureate.",
  },
  {
    year: 1986,
    authors: "Bollerslev, T.",
    title: "Generalized autoregressive conditional heteroskedasticity",
    journal: "Journal of Econometrics",
    logo: "journal-of-econometrics.png",
    ref: "31(3), 307–327",
    note: "",
    category: "Foundations",
    why: [
      "Generalized ARCH so variance depends on past variances as well as past shocks.",
      "GARCH became the workhorse model for volatility forecasting and risk management.",
      "Far more parsimonious than high-order ARCH for persistent volatility.",
    ],
    authorNote: "Tim Bollerslev, professor of economics at Duke University.",
  },
  {
    year: 1987,
    authors: "Engle, R. F., & Granger, C. W. J.",
    title: "Co-integration and error correction: Representation, estimation, and testing",
    journal: "Econometrica",
    logo: "econometrica.png",
    ref: "55(2), 251–276",
    note: "",
    category: "Foundations",
    why: [
      "Formalized cointegration: long-run equilibrium relationships among non-stationary series.",
      "Introduced the error-correction representation linking short-run dynamics to long-run levels.",
      "Statistical foundation for pairs trading and statistical arbitrage.",
    ],
    authorNote: "Robert Engle (NYU) and Clive Granger (UC San Diego), both Nobel laureates.",
  },
  {
    year: 2001,
    authors: "Cont, R.",
    title: "Empirical properties of asset returns: Stylized facts and statistical issues",
    journal: "Quantitative Finance",
    logo: "quantitative-finance.png",
    ref: "1(2), 223–236",
    note: "",
    category: "Foundations",
    why: [
      "Catalogued the empirical “stylized facts” of returns: fat tails, volatility clustering, leverage effects.",
      "Set out properties any realistic price model must reproduce.",
      "Widely used reference framing for model validation.",
    ],
    authorNote: "Rama Cont, professor of mathematics at the University of Oxford.",
  },
  {
    year: 1977,
    authors: "Vasicek, O.",
    title: "An equilibrium characterization of the term structure",
    journal: "Journal of Financial Economics",
    logo: "journal-of-financial-economics.webp",
    ref: "5(2), 177–188",
    note: "",
    category: "Fixed Income & Interest-Rate Modeling",
    why: [
      "First equilibrium model of the whole term structure from a single short-rate process.",
      "Introduced a mean-reverting Ornstein-Uhlenbeck dynamic for interest rates.",
      "Yields closed-form bond prices and tractable analytics.",
    ],
    authorNote: "Oldrich Vasicek, quantitative finance pioneer and KMV co-founder.",
  },
  {
    year: 1985,
    authors: "Cox, J. C., Ingersoll, J. E., & Ross, S. A.",
    title: "A theory of the term structure of interest rates",
    journal: "Econometrica",
    logo: "econometrica.png",
    ref: "53(2), 385–407",
    note: "",
    category: "Fixed Income & Interest-Rate Modeling",
    why: [
      "General-equilibrium model of the term structure of interest rates.",
      "Introduced the square-root (CIR) process that keeps rates non-negative.",
      "Cornerstone of fixed-income and credit modeling.",
    ],
    authorNote: "John Cox, Jonathan Ingersoll, and Stephen Ross, leading financial economists.",
  },
  {
    year: 1990,
    authors: "Hull, J., & White, A.",
    title: "Pricing interest-rate-derivative securities",
    journal: "The Review of Financial Studies",
    logo: "review-of-financial-studies.png",
    ref: "3(4), 573–592",
    note: "",
    category: "Fixed Income & Interest-Rate Modeling",
    why: [
      "Extended Vasicek to fit the initial yield curve exactly via time-dependent parameters.",
      "Made no-arbitrage short-rate models calibratable to market data.",
      "Widely used for pricing interest-rate derivatives.",
    ],
    authorNote: "John Hull and Alan White, professors at the University of Toronto.",
  },
  {
    year: 1992,
    authors: "Heath, D., Jarrow, R., & Morton, A.",
    title: "Bond pricing and the term structure of interest rates: A new methodology for contingent claims valuation",
    journal: "Econometrica",
    logo: "econometrica.png",
    ref: "60(1), 77–105",
    note: "",
    category: "Fixed Income & Interest-Rate Modeling",
    why: [
      "Modeled the entire forward-rate curve under no-arbitrage rather than a single short rate.",
      "Showed the drift of forward rates is fully determined by their volatility structure.",
      "Unifying framework underpinning modern interest-rate modeling.",
    ],
    authorNote: "David Heath, Robert Jarrow, and Andrew Morton, Cornell-based researchers.",
  },
  {
    year: 1997,
    authors: "Brace, A., Gatarek, D., & Musiela, M.",
    title: "The market model of interest rate dynamics",
    journal: "Mathematical Finance",
    logo: "mathematical-finance.png",
    ref: "7(2), 127–155",
    note: "",
    category: "Fixed Income & Interest-Rate Modeling",
    why: [
      "Modeled discrete, market-observable forward LIBOR rates directly.",
      "Made Black’s market formulas for caps and swaptions internally consistent.",
      "Basis of the LIBOR Market Model used on rates desks.",
    ],
    authorNote: "Alan Brace, Dariusz Gatarek, and Marek Musiela, rates quants and academics.",
  },
  {
    year: 1974,
    authors: "Merton, R. C.",
    title: "On the pricing of corporate debt: The risk structure of interest rates",
    journal: "The Journal of Finance",
    logo: "journal-of-finance.jpg",
    ref: "29(2), 449–470",
    note: "",
    category: "Fixed Income & Interest-Rate Modeling",
    why: [
      "Modeled corporate debt and equity as options on the value of the firm.",
      "Founded the structural approach to credit risk (the “Merton model”).",
      "Basis for the KMV / Moody’s default-probability framework.",
    ],
    authorNote: "Robert C. Merton, MIT/Harvard; 1997 Nobel laureate.",
  },
  {
    year: 1973,
    authors: "Black, F., & Scholes, M.",
    title: "The pricing of options and corporate liabilities",
    journal: "Journal of Political Economy",
    logo: "journal-of-political-economy.png",
    ref: "81(3), 637–654",
    note: "",
    category: "Derivatives, Options & Volatility",
    why: [
      "Derived a closed-form price for European options via a riskless replicating portfolio.",
      "Established no-arbitrage, dynamic-hedging pricing as the basis of derivatives.",
      "The single most influential result in quantitative finance.",
    ],
    authorNote: "Fischer Black and Myron Scholes; Scholes shared the 1997 Nobel Prize.",
  },
  {
    year: 1973,
    authors: "Merton, R. C.",
    title: "Theory of rational option pricing",
    journal: "The Bell Journal of Economics and Management Science",
    logo: "bell-journal-of-economics.svg",
    ref: "4(1), 141–183",
    note: "",
    category: "Derivatives, Options & Volatility",
    why: [
      "Provided rigorous continuous-time foundations for option pricing.",
      "Extended Black-Scholes to dividends, stochastic rates, and general claims.",
      "Established the dynamic-hedging / no-arbitrage methodology.",
    ],
    authorNote: "Robert C. Merton, MIT/Harvard; shared the 1997 Nobel Prize.",
  },
  {
    year: 1979,
    authors: "Cox, J. C., Ross, S. A., & Rubinstein, M.",
    title: "Option pricing: A simplified approach",
    journal: "Journal of Financial Economics",
    logo: "journal-of-financial-economics.webp",
    ref: "7(3), 229–263",
    note: "",
    category: "Derivatives, Options & Volatility",
    why: [
      "Introduced the binomial-tree model for option pricing.",
      "Priced options by backward induction in discrete time.",
      "Made no-arbitrage option pricing intuitive and broadly teachable.",
    ],
    authorNote: "John Cox, Stephen Ross, and Mark Rubinstein, financial economists.",
  },
  {
    year: 1976,
    authors: "Ross, S. A.",
    title: "Options and efficiency",
    journal: "The Quarterly Journal of Economics",
    logo: "quarterly-journal-of-economics.png",
    ref: "90(1), 75–89",
    note: "",
    category: "Derivatives, Options & Volatility",
    why: [
      "Showed options can complete markets by spanning otherwise unattainable payoffs.",
      "Connected option payoffs to state (Arrow-Debreu) prices.",
      "Theoretical underpinning of risk-neutral / state pricing.",
    ],
    authorNote: "Stephen A. Ross, MIT Sloan; originator of arbitrage pricing.",
  },
  {
    year: 1976,
    authors: "Merton, R. C.",
    title: "Option pricing when underlying stock returns are discontinuous",
    journal: "Journal of Financial Economics",
    logo: "journal-of-financial-economics.webp",
    ref: "3(1–2), 125–144",
    note: "",
    category: "Derivatives, Options & Volatility",
    why: [
      "Added discontinuous jumps to the price process underlying options.",
      "Helped explain implied-volatility smiles missed by Black-Scholes.",
      "Foundational jump-diffusion model for derivatives.",
    ],
    authorNote: "Robert C. Merton, MIT/Harvard; 1997 Nobel laureate.",
  },
  {
    year: 1979,
    authors: "Geske, R.",
    title: "The valuation of compound options",
    journal: "Journal of Financial Economics",
    logo: "journal-of-financial-economics.webp",
    ref: "7(1), 63–81",
    note: "",
    category: "Derivatives, Options & Volatility",
    why: [
      "Priced options on options (compound options) in closed form.",
      "Modeled equity as an option on the firm, advancing structural credit theory.",
      "Influential for sequential and staged-decision valuation.",
    ],
    authorNote: "Robert Geske, professor at UCLA Anderson.",
  },
  {
    year: 1993,
    authors: "Heston, S. L.",
    title: "A closed-form solution for options with stochastic volatility with applications to bond and currency options",
    journal: "The Review of Financial Studies",
    logo: "review-of-financial-studies.png",
    ref: "6(2), 327–343",
    note: "",
    category: "Derivatives, Options & Volatility",
    why: [
      "Closed-form option prices when volatility itself follows a stochastic process.",
      "Captures volatility smiles and skews via mean-reverting variance.",
      "The standard stochastic-volatility model on derivatives desks.",
    ],
    authorNote: "Steven Heston, professor at the University of Maryland.",
  },
  {
    year: 1952,
    authors: "Markowitz, H.",
    title: "Portfolio selection",
    journal: "The Journal of Finance",
    logo: "journal-of-finance.jpg",
    ref: "7(1), 77–91",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Founded modern portfolio theory via mean-variance optimization.",
      "Formalized diversification and the efficient frontier.",
      "Recognized by the 1990 Nobel Prize.",
    ],
    authorNote: "Harry Markowitz; 1990 Nobel laureate in economics.",
  },
  {
    year: 1958,
    authors: "Tobin, J.",
    title: "Liquidity preference as behavior towards risk",
    journal: "The Review of Economic Studies",
    logo: "review-of-economic-studies.png",
    ref: "25(2), 65–86",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Showed investors separate the choice of risky-asset mix from how much to hold risk-free.",
      "Established the two-fund separation theorem underpinning the CAPM.",
      "Linked portfolio theory to liquidity preference.",
    ],
    authorNote: "James Tobin, Yale economist; 1981 Nobel laureate.",
  },
  {
    year: 1964,
    authors: "Sharpe, W. F.",
    title: "Capital asset prices: A theory of market equilibrium under conditions of risk",
    journal: "The Journal of Finance",
    logo: "journal-of-finance.jpg",
    ref: "19(3), 425–442",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Derived the Capital Asset Pricing Model linking expected return to market beta.",
      "Introduced the split between systematic and diversifiable risk.",
      "Recognized by the 1990 Nobel Prize.",
    ],
    authorNote: "William F. Sharpe, professor at Stanford; 1990 Nobel laureate.",
  },
  {
    year: 1965,
    authors: "Lintner, J.",
    title: "The valuation of risk assets and the selection of risky investments in stock portfolios and capital budgets",
    journal: "The Review of Economics and Statistics",
    logo: "review-of-economics-and-statistics.png",
    ref: "47(1), 13–37",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Independently derived CAPM in a portfolio and capital-budgeting setting.",
      "Extended equilibrium pricing to corporate investment decisions.",
      "Co-foundation of the CAPM framework.",
    ],
    authorNote: "John Lintner, professor at Harvard Business School.",
  },
  {
    year: 1970,
    authors: "Fama, E. F.",
    title: "Efficient capital markets: A review of theory and empirical work",
    journal: "The Journal of Finance",
    logo: "journal-of-finance.jpg",
    ref: "25(2), 383–417",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Synthesized and formalized the Efficient Market Hypothesis.",
      "Defined weak, semi-strong, and strong forms of efficiency.",
      "The reference statement of market efficiency.",
    ],
    authorNote: "Eugene Fama, University of Chicago; 2013 Nobel laureate.",
  },
  {
    year: 1976,
    authors: "Ross, S. A.",
    title: "The arbitrage theory of capital asset pricing",
    journal: "Journal of Economic Theory",
    logo: "journal-of-economic-theory.png",
    ref: "13(3), 341–360",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Introduced Arbitrage Pricing Theory as a multi-factor alternative to CAPM.",
      "Priced assets via exposure to systematic factors under no-arbitrage.",
      "Foundation of modern multi-factor models.",
    ],
    authorNote: "Stephen A. Ross, MIT Sloan.",
  },
  {
    year: 1993,
    authors: "Jegadeesh, N., & Titman, S.",
    title: "Returns to buying winners and selling losers: Implications for stock market efficiency",
    journal: "The Journal of Finance",
    logo: "journal-of-finance.jpg",
    ref: "48(1), 65–91",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Documented that past winners continue to outperform past losers (momentum).",
      "Posed a durable challenge to market efficiency.",
      "Spawned the momentum-factor literature.",
    ],
    authorNote: "Narasimhan Jegadeesh and Sheridan Titman, finance professors.",
  },
  {
    year: 1992,
    authors: "Fama, E. F., & French, K. R.",
    title: "The cross-section of expected stock returns",
    journal: "The Journal of Finance",
    logo: "journal-of-finance.jpg",
    ref: "47(2), 427–465",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Showed size and book-to-market explain returns beyond CAPM beta.",
      "Empirically undercut beta as the sole risk measure.",
      "Set the stage for multi-factor asset pricing.",
    ],
    authorNote: "Eugene Fama and Kenneth French (Chicago / Dartmouth).",
  },
  {
    year: 1993,
    authors: "Fama, E. F., & French, K. R.",
    title: "Common risk factors in the returns on stocks and bonds",
    journal: "Journal of Financial Economics",
    logo: "journal-of-financial-economics.webp",
    ref: "33(1), 3–56",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Formalized the three-factor (market, size, value) model.",
      "Became the empirical benchmark for performance attribution.",
      "Cornerstone of factor investing.",
    ],
    authorNote: "Eugene Fama and Kenneth French.",
  },
  {
    year: 1997,
    authors: "Carhart, M. M.",
    title: "On persistence in mutual fund performance",
    journal: "The Journal of Finance",
    logo: "journal-of-finance.jpg",
    ref: "52(1), 57–82",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Added a momentum factor to the Fama-French model.",
      "Standard four-factor model for evaluating fund performance.",
      "Showed fund-return persistence largely reflects momentum.",
    ],
    authorNote: "Mark Carhart, financial economist and practitioner.",
  },
  {
    year: 2015,
    authors: "Fama, E. F., & French, K. R.",
    title: "A five-factor asset pricing model",
    journal: "Journal of Financial Economics",
    logo: "journal-of-financial-economics.webp",
    ref: "116(1), 1–22",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Added profitability and investment factors to the three-factor model.",
      "Updated benchmark for modern factor research.",
      "Reflects accounting-based drivers of returns.",
    ],
    authorNote: "Eugene Fama and Kenneth French.",
  },
  {
    year: 2004,
    authors: "Lo, A. W.",
    title: "The adaptive markets hypothesis",
    journal: "The Journal of Portfolio Management",
    logo: "journal-of-portfolio-management.png",
    ref: "30(5), 15–29",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Reconciled efficient markets with behavioral finance via an evolutionary lens.",
      "Framed market behavior as adapting to changing conditions.",
      "Influential bridge between rationalist and behavioral views.",
    ],
    authorNote: "Andrew W. Lo, professor at MIT Sloan.",
  },
  {
    year: 2016,
    authors: "Harvey, C. R., Liu, Y., & Zhu, H.",
    title: "… and the cross-section of expected returns",
    journal: "The Review of Financial Studies",
    logo: "review-of-financial-studies.png",
    ref: "29(1), 5–68",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Argued most “discovered” return factors fail proper multiple-testing standards.",
      "Proposed higher statistical hurdles for claimed anomalies.",
      "Central reference for the replication debate in asset pricing.",
    ],
    authorNote: "Campbell Harvey (Duke), Yan Liu, and Heqing Zhu.",
  },
  {
    year: 1992,
    authors: "Black, F., & Litterman, R.",
    title: "Global portfolio optimization",
    journal: "Financial Analysts Journal",
    logo: "financial-analysts-journal.png",
    ref: "48(5), 28–43",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Combined market-equilibrium returns with investor views via Bayesian blending.",
      "Cured the instability and extreme weights of naive mean-variance optimization.",
      "Widely used in institutional asset allocation.",
    ],
    authorNote: "Fischer Black and Robert Litterman, Goldman Sachs.",
  },
  {
    year: 2006,
    authors: "Thorp, E. O.",
    title: "The Kelly criterion in blackjack, sports betting, and the stock market",
    journal: "In S. A. Zenios & W. T. Ziemba (Eds.)",
    ref: "Handbook of asset and liability management (Vol. 1, pp. 385–428). North-Holland",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Applied the Kelly criterion to position sizing and long-run capital growth.",
      "Linked optimal bet sizing to leverage and growth optimization.",
      "Widely used framework in quantitative trading.",
    ],
    authorNote: "Edward O. Thorp, mathematician and hedge-fund pioneer.",
  },
  {
    year: 2004,
    authors: "Ledoit, O., & Wolf, M.",
    title: "Honey, I shrunk the sample covariance matrix",
    journal: "The Journal of Portfolio Management",
    logo: "journal-of-portfolio-management.png",
    ref: "30(4), 110–119",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Introduced shrinkage estimation of the covariance matrix.",
      "Made portfolio optimization stable in high dimensions.",
      "Now standard practice in systematic portfolio construction.",
    ],
    authorNote: "Olivier Ledoit and Michael Wolf, University of Zurich.",
  },
  {
    year: 2016,
    authors: "López de Prado, M.",
    title: "Building diversified portfolios that outperform out of sample",
    journal: "The Journal of Portfolio Management",
    logo: "journal-of-portfolio-management.png",
    ref: "42(4), 59–69",
    note: "",
    category: "Portfolio Optimization & Asset Allocation",
    why: [
      "Introduced Hierarchical Risk Parity using clustering and graph structure.",
      "Avoided unstable covariance-matrix inversion in optimization.",
      "Improved out-of-sample portfolio robustness.",
    ],
    authorNote: "Marcos López de Prado, quant researcher and professor (Cornell).",
  },
  {
    year: 1999,
    authors: "Artzner, P., Delbaen, F., Eber, J.-M., & Heath, D.",
    title: "Coherent measures of risk",
    journal: "Mathematical Finance",
    logo: "mathematical-finance.png",
    ref: "9(3), 203–228",
    note: "",
    category: "Risk Management",
    why: [
      "Axiomatized what makes a risk measure “coherent.”",
      "Exposed VaR’s failure of subadditivity, motivating Expected Shortfall.",
      "Theoretical foundation of modern risk measurement.",
    ],
    authorNote: "Artzner, Delbaen, Eber, and Heath, mathematical-finance researchers.",
  },
  {
    year: 2000,
    authors: "Rockafellar, R. T., & Uryasev, S.",
    title: "Optimization of conditional value-at-risk",
    journal: "The Journal of Risk",
    logo: "journal-of-risk.svg",
    ref: "2(3), 21–41",
    note: "",
    category: "Risk Management",
    why: [
      "Made Conditional Value-at-Risk optimization tractable via linear programming.",
      "Provided a coherent, optimizable downside-risk measure.",
      "Widely adopted in portfolio and risk optimization.",
    ],
    authorNote: "R. Tyrrell Rockafellar (Washington) and Stanislav Uryasev (Florida).",
  },
  {
    year: 2000,
    authors: "McNeil, A. J., & Frey, R.",
    title: "Estimation of tail-related risk measures for heteroscedastic financial time series: An extreme value approach",
    journal: "Journal of Empirical Finance",
    logo: "journal-of-empirical-finance.png",
    ref: "7(3–4), 271–300",
    note: "",
    category: "Risk Management",
    why: [
      "Combined GARCH filtering with Extreme Value Theory for tail risk.",
      "Estimated conditional VaR and Expected Shortfall directly in the tails.",
      "Influential framework for dynamic extreme-risk measurement.",
    ],
    authorNote: "Alexander McNeil and Rüdiger Frey, quantitative-risk researchers.",
  },
  {
    year: 1985,
    authors: "Kyle, A. S.",
    title: "Continuous auctions and insider trading",
    journal: "Econometrica",
    logo: "econometrica.png",
    ref: "53(6), 1315–1335",
    note: "",
    category: "Market Microstructure & Execution",
    why: [
      "Modeled how informed traders’ orders move prices (Kyle’s lambda).",
      "Formalized market depth, liquidity, and price impact.",
      "Cornerstone of market-microstructure theory.",
    ],
    authorNote: "Albert S. Kyle, professor at the University of Maryland.",
  },
  {
    year: 1985,
    authors: "Glosten, L. R., & Milgrom, P. R.",
    title: "Bid, ask and transaction prices in a specialist market with heterogeneously informed traders",
    journal: "Journal of Financial Economics",
    logo: "journal-of-financial-economics.webp",
    ref: "14(1), 71–100",
    note: "",
    category: "Market Microstructure & Execution",
    why: [
      "Showed bid-ask spreads arise from adverse selection against informed traders.",
      "Explained spreads even with zero order-processing costs.",
      "Foundational microstructure model of price formation.",
    ],
    authorNote: "Lawrence Glosten (Columbia) and Paul Milgrom (Stanford).",
  },
  {
    year: 2001,
    authors: "Almgren, R., & Chriss, N.",
    title: "Optimal execution of portfolio transactions",
    journal: "The Journal of Risk",
    logo: "journal-of-risk.svg",
    ref: "3(2), 5–39",
    note: "",
    category: "Market Microstructure & Execution",
    why: [
      "Framed optimal trade execution as a cost/risk trade-off.",
      "Derived efficient trading trajectories balancing impact and timing risk.",
      "Foundation of modern execution algorithms.",
    ],
    authorNote: "Robert Almgren and Neil Chriss, quant practitioners and academics.",
  },
  {
    year: 2008,
    authors: "Avellaneda, M., & Stoikov, S.",
    title: "High-frequency trading in a limit order book",
    journal: "Quantitative Finance",
    logo: "quantitative-finance.png",
    ref: "8(3), 217–224",
    note: "",
    category: "Market Microstructure & Execution",
    why: [
      "Derived optimal bid/ask quotes for an inventory-averse market maker.",
      "Linked quoting to inventory risk and order-arrival dynamics.",
      "Standard reference for high-frequency market-making.",
    ],
    authorNote: "Marco Avellaneda (NYU Courant) and Sasha Stoikov (Cornell).",
  },
  {
    year: 2010,
    authors: "Avellaneda, M., & Lee, J.-H.",
    title: "Statistical arbitrage in the U.S",
    journal: "equities market. Quantitative Finance",
    logo: "quantitative-finance.png",
    ref: "10(7), 761–782",
    note: "",
    category: "Algorithmic Trading & Machine Learning",
    why: [
      "Built systematic stat-arb signals from PCA and mean-reversion of residuals.",
      "Provided a rigorous, implementable equity statistical-arbitrage framework.",
      "Widely cited template for relative-value strategies.",
    ],
    authorNote: "Marco Avellaneda (NYU) and Jeong-Hyun Lee.",
  },
  {
    year: 2020,
    authors: "Gu, S., Kelly, B., & Xiu, D.",
    title: "Empirical asset pricing via machine learning",
    journal: "The Review of Financial Studies",
    logo: "review-of-financial-studies.png",
    ref: "33(5), 2223–2273",
    note: "",
    category: "Algorithmic Trading & Machine Learning",
    why: [
      "Benchmarked machine-learning methods for predicting asset returns.",
      "Showed trees and neural nets outperform linear models out-of-sample.",
      "The reference paper for machine learning in asset pricing.",
    ],
    authorNote: "Shihao Gu, Bryan Kelly (Yale), and Dacheng Xiu (Chicago Booth).",
  },
  {
    year: 2019,
    authors: "Kelly, B. T., Pruitt, S., & Su, Y.",
    title: "Characteristics are covariances: A unified model of risk and return",
    journal: "Journal of Financial Economics",
    logo: "journal-of-financial-economics.webp",
    ref: "134(3), 501–524",
    note: "",
    category: "Algorithmic Trading & Machine Learning",
    why: [
      "Introduced Instrumented PCA linking characteristics to latent factor loadings.",
      "Unified characteristic- and covariance-based explanations of returns.",
      "Influential modern factor-modeling method.",
    ],
    authorNote: "Bryan Kelly, Seth Pruitt, and Yinan Su.",
  },
  {
    year: 2014,
    authors: "Bailey, D. H., Borwein, J. M., López de Prado, M., & Zhu, Q. J.",
    title: "Pseudo-mathematics and financial charlatanism: The effects of backtest overfitting on out-of-sample performance",
    journal: "Notices of the American Mathematical Society",
    logo: "notices-of-the-ams.png",
    ref: "61(5), 458–471",
    note: "",
    category: "Algorithmic Trading & Machine Learning",
    why: [
      "Showed how easily backtests overfit to produce spurious strategies.",
      "Quantified the minimum backtest length needed to avoid false discoveries.",
      "Widely cited warning on data-mined trading rules.",
    ],
    authorNote: "David Bailey, Jonathan Borwein, Marcos López de Prado, and Qiji Zhu.",
  },
  {
    year: 2014,
    authors: "Bailey, D. H., & López de Prado, M.",
    title: "The deflated Sharpe ratio: Correcting for selection bias, backtest overfitting, and non-normality",
    journal: "The Journal of Portfolio Management",
    logo: "journal-of-portfolio-management.png",
    ref: "40(5), 94–107",
    note: "",
    category: "Algorithmic Trading & Machine Learning",
    why: [
      "Corrected the Sharpe ratio for selection bias and non-normality.",
      "Provided a test for whether a track record is statistically real.",
      "Practical tool against backtest overfitting.",
    ],
    authorNote: "David H. Bailey and Marcos López de Prado.",
  },
  {
    year: 2017,
    authors: "Bailey, D. H., Borwein, J. M., López de Prado, M., & Zhu, Q. J.",
    title: "The probability of backtest overfitting",
    journal: "Journal of Computational Finance",
    logo: "journal-of-computational-finance.svg",
    ref: "20(4), 39–69",
    note: "",
    category: "Algorithmic Trading & Machine Learning",
    why: [
      "Formalized the probability that the best backtested strategy is overfit.",
      "Introduced combinatorially symmetric cross-validation.",
      "Rigorous framework for evaluating strategy research.",
    ],
    authorNote: "Bailey, Borwein, López de Prado, and Zhu.",
  },
  {
    year: 2019,
    authors: "Zhang, Z., Zohren, S., & Roberts, S.",
    title: "DeepLOB: Deep convolutional neural networks for limit order books",
    journal: "IEEE Transactions on Signal Processing",
    logo: "ieee-transactions-signal-processing.png",
    ref: "67(11), 3001–3012",
    note: "",
    category: "Algorithmic Trading & Machine Learning",
    why: [
      "Applied deep CNNs and LSTMs to raw limit-order-book data.",
      "Predicted short-horizon price moves directly from order flow.",
      "Influential template for deep learning in microstructure.",
    ],
    authorNote: "Zihao Zhang, Stefan Zohren, and Stephen Roberts (University of Oxford).",
  },
  {
    year: 2020,
    authors: "Zhang, Z., Zohren, S., & Roberts, S.",
    title: "Deep learning for portfolio optimization",
    journal: "The Journal of Financial Data Science",
    logo: "journal-of-financial-data-science.svg",
    ref: "2(4), 8–20",
    note: "",
    category: "Algorithmic Trading & Machine Learning",
    why: [
      "Trained neural networks to output portfolio weights directly from data.",
      "Optimized the Sharpe ratio end-to-end, skipping return forecasts.",
      "A notable modern deep-learning approach to allocation.",
    ],
    authorNote: "Zihao Zhang, Stefan Zohren, and Stephen Roberts (University of Oxford).",
  },
];

export const BOOK_COUNT = BOOK_GROUPS.reduce((n, g) => n + g.books.length, 0);
export const PAPER_COUNT = PAPERS.length;
export const PAPER_REC_COUNT = PAPER_RECS.length;
