import type { Metadata } from "next";
import { CategoryView } from "@/components/research/CategoryView";

/* GENERATED by quant/gen_category_pages.py — edit CategoryView, not this. */

export const metadata: Metadata = {
  title: "Quant Finance Foundations — Research — pyportfolios",
  description: "The bedrock — valuation, pricing, and the mathematics every model inherits.",
};

export default function Page() {
  return <CategoryView category="quant-finance-foundations" />;
}
