/* ============================================================================
   The reusable article template (reference §B). Dark global nav → light Pale
   Sisal reading surface. Sticky scroll-spy TOC rail (desktop), Lora title,
   metadata byline, a notebook badge, the body, then a notebook CTA + prev/next.
   ========================================================================== */

import type { ReactNode } from "react";
import { TransitionLink } from "@/components/motion/TransitionLink";
import {
  type Article,
  CATEGORIES,
  articleNeighbours,
} from "@/lib/articles";
import { ArticleNav } from "@/components/article/ArticleNav";
import { ArticleToc } from "@/components/article/ArticleToc";
import { ScrollReveal } from "@/components/motion/ScrollReveal";
import { ReadingProgress } from "@/components/motion/ReadingProgress";

function NotebookBadge({ href }: { href: string }) {
  return (
    <a
      href={href}
      download
      className="group inline-flex items-center gap-1.5 rounded-sm border border-aqua/40 px-2.5 py-1 t-mono text-[0.66rem] uppercase tracking-[0.12em] text-aqua transition-colors hover:bg-aqua hover:text-anthracite"
    >
      <span className="h-1.5 w-1.5 rounded-full bg-aqua group-hover:bg-anthracite" aria-hidden="true" />
      Notebook
      <span aria-hidden="true" className="transition-transform group-hover:translate-y-0.5">↓</span>
    </a>
  );
}

export function ArticleLayout({ article, children }: { article: Article; children: ReactNode }) {
  const category = CATEGORIES[article.category];
  const notebookHref = `/notebooks/${article.notebook}`;
  const { prev, next } = articleNeighbours(article.slug);

  return (
    <div className="min-h-screen bg-anthracite">
      <ReadingProgress />
      <ScrollReveal />
      <ArticleNav />

      <article className="editorial-dark bg-anthracite text-pearl">
        <div className="mx-auto max-w-6xl px-6 lg:grid lg:grid-cols-[15rem_minmax(0,1fr)] lg:gap-12 lg:px-8">
          {/* -------------------------------------------------- TOC rail -- */}
          <aside className="hidden lg:block">
            <div className="sticky top-28 py-16">
              <TransitionLink
                href="/research"
                className="t-mono text-[0.66rem] uppercase tracking-[0.18em] text-steel transition-colors hover:text-aqua"
              >
                ← Research
              </TransitionLink>
              <div className="mt-8">
                <ArticleToc sections={article.sections} />
              </div>
              <div className="mt-10 border-t border-pearl/10 pt-6">
                <NotebookBadge href={notebookHref} />
              </div>
            </div>
          </aside>

          {/* ------------------------------------------------- article col -- */}
          <div className="min-w-0 py-16 lg:max-w-[46rem] lg:py-20">
            {/* header */}
            <header className="border-b border-pearl/10 pb-9">
              <div className="flex items-center gap-3">
                <TransitionLink
                  href={`/research#${category.slug}`}
                  className="t-mono text-xs uppercase tracking-[0.2em] text-aqua transition-colors hover:text-pearl"
                >
                  {category.numeral} · {category.name}
                </TransitionLink>
              </div>

              <h1 className="mt-5 font-sans text-[2.5rem] leading-[1.02] tracking-tight text-pearl md:text-[3.5rem]" style={{ fontWeight: 900 }}>
                {article.title}
              </h1>
              <p className="mt-6 max-w-2xl rounded-sm border border-aqua/25 px-4 py-3 t-mono text-[0.9rem] italic leading-relaxed text-mist">
                {article.dek}
              </p>

              <p className="mt-7 t-mono text-[0.72rem] text-steel/80">
                <span className="text-steel">Stack — </span>
                {article.stack.join(" · ")}
                <span className="ml-auto float-right lg:hidden">
                  <NotebookBadge href={notebookHref} />
                </span>
              </p>
            </header>

            {/* body */}
            <div className="article-body">{children}</div>

            {/* notebook CTA */}
            <aside className="corner-ticks mt-16 flex flex-col items-start justify-between gap-5 rounded-sm border border-pearl/10 bg-coal p-7 sm:flex-row sm:items-center">
              <div>
                <p className="t-mono text-[0.66rem] uppercase tracking-[0.2em] text-aqua">Run it yourself</p>
                <p className="mt-2 font-serif text-xl text-pearl">The full, reproducible notebook.</p>
                <p className="mt-1 text-sm text-steel">Every figure and table in this article is generated by this notebook.</p>
              </div>
              <a
                href={notebookHref}
                download
                className="group inline-flex shrink-0 items-center gap-2 rounded-sm bg-pearl px-6 py-3 text-sm font-semibold text-anthracite transition-colors duration-300 hover:bg-aqua"
              >
                Download notebook
                <span className="t-mono text-xs opacity-70">.ipynb</span>
                <span aria-hidden="true" className="transition-transform duration-300 group-hover:translate-y-0.5">↓</span>
              </a>
            </aside>

            {/* prev / next */}
            <nav className="mt-12 grid gap-px overflow-hidden rounded-sm border border-pearl/10 bg-pearl/10 sm:grid-cols-2">
              {prev ? (
                <TransitionLink href={`/research/${prev.slug}`} className="group bg-coal px-6 py-5 transition-colors hover:bg-white/5">
                  <span className="t-mono text-[0.62rem] uppercase tracking-[0.18em] text-steel">← Previous</span>
                  <p className="mt-2 font-serif text-lg leading-snug text-pearl group-hover:text-aqua">{prev.title}</p>
                </TransitionLink>
              ) : <span className="bg-coal" />}
              {next ? (
                <TransitionLink href={`/research/${next.slug}`} className="group bg-coal px-6 py-5 text-right transition-colors hover:bg-white/5">
                  <span className="t-mono text-[0.62rem] uppercase tracking-[0.18em] text-steel">Next →</span>
                  <p className="mt-2 font-serif text-lg leading-snug text-pearl group-hover:text-aqua">{next.title}</p>
                </TransitionLink>
              ) : <span className="bg-coal" />}
            </nav>
          </div>
        </div>
      </article>

      {/* colophon */}
      <footer className="bg-pitch">
        <div className="mx-auto flex max-w-6xl flex-col justify-between gap-3 px-6 py-10 t-mono text-[0.66rem] uppercase tracking-[0.16em] text-steel sm:flex-row lg:px-8">
          <span>© 2026 pyportfolios. All rights reserved.</span>
          <span>Where finance theory, coding &amp; markets converge · <span className="text-aqua">pyportfolios.com</span></span>
        </div>
      </footer>
    </div>
  );
}
