"""
Legacy upgrade - Black-Scholes from first principles (finance-fundamentals).
Assets: QQQ daily closes 2017-2024 (realised vol, spot) + ^IRX Dec 2024 (risk-free).
Libs: NumPy Pandas SciPy scikit-learn yfinance.

Replaces the hand-drawn smile + made-up Greek table with real computed results:
  - rolling 1y realised vol of QQQ (the "constant sigma" assumption, tested),
  - price + Greeks for a real ATM 1y QQQ contract (spot/vol/rate all observed),
  - the call price curve C(S) vs intrinsic value,
  - a vol smile generated by a 2-state Gaussian mixture calibrated to QQQ
    returns (seeded), inverted back through Black-Scholes strike by strike.

Data: reuses quant/data/t02_black_scholes.csv (QQQ, shared cache). The risk-free
rate self-caches to quant/data/legacy_black-scholes-from-first-principles.csv
(downloaded via yfinance if missing). Deterministic: seed 42.
Emits the article data module + the runnable notebook (vault/notebooks).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yfinance as yf
from scipy import stats
from scipy.optimize import brentq
from scipy.stats import norm
from sklearn.mixture import GaussianMixture

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from emit import DATA, TS_OUT, code, downsample, load, md, r, write_nb, year_labels  # noqa: E402

SLUG = "black-scholes-from-first-principles"
SEED = 42
T_YEARS = 1.0


def write_ts(slug: str, payload: dict) -> Path:
    """Local variant of emit.write_ts with the correct rebuild path."""
    TS_OUT.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, indent=2, allow_nan=False)
    src = (
        "/* GENERATED by quant pipeline — do not hand-edit.\n"
        "   Rebuild: python quant/legacy/bs_first_principles.py\n"
        "   Real computed results; charts render these via DataCharts.tsx. */\n\n"
        f"const data = {body} as const;\n\nexport default data;\n"
    )
    out = TS_OUT / f"{slug}.ts"
    out.write_text(src, encoding="utf-8")
    return out


def self_cache_rate() -> pd.DataFrame:
    """^IRX (13-week T-bill discount yield, in percent), December 2024."""
    out = DATA / f"legacy_{SLUG}.csv"
    if not out.exists():
        df = yf.download("^IRX", start="2024-12-01", end="2025-01-01",
                         auto_adjust=True, progress=False)
        close = df["Close"]
        if isinstance(close, pd.DataFrame):
            close.columns = ["^IRX"]
        else:
            close = close.to_frame("^IRX")
        close.dropna().to_csv(out)
    return load(f"legacy_{SLUG}")


# ------------------------------------------------------------ closed form --

def bs_price(S, K, T, rf, sigma, kind="call"):
    d1 = (np.log(S / K) + (rf + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    if kind == "call":
        return S * norm.cdf(d1) - K * np.exp(-rf * T) * norm.cdf(d2)
    return K * np.exp(-rf * T) * norm.cdf(-d2) - S * norm.cdf(-d1)


def bs_greeks(S, K, T, rf, sigma):
    d1 = (np.log(S / K) + (rf + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    pdf = norm.pdf(d1)
    return {
        "delta": norm.cdf(d1),
        "gamma": pdf / (S * sigma * np.sqrt(T)),
        "vega": S * pdf * np.sqrt(T) / 100,
        "theta": (-(S * pdf * sigma) / (2 * np.sqrt(T))
                  - rf * K * np.exp(-rf * T) * norm.cdf(d2)) / 365,
        "rho": K * T * np.exp(-rf * T) * norm.cdf(d2) / 100,
    }


def main() -> None:
    px = load("t02_black_scholes")["QQQ"].dropna()
    logret = np.log(px / px.shift(1)).dropna()

    # --- 1 - the "constant sigma" assumption, tested -----------------------
    roll252 = (logret.rolling(252).std(ddof=1) * np.sqrt(252)).dropna()
    roll21 = (logret.rolling(21).std(ddof=1) * np.sqrt(21 * 12)).dropna()
    vol_min, vol_max = float(roll252.min()), float(roll252.max())
    vol_last = float(roll252.iloc[-1])
    vol21_max = float(roll21.max())
    vol21_max_date = str(roll21.idxmax().date())

    # --- 2 - a real contract: ATM 1y call on QQQ ---------------------------
    rate = self_cache_rate()["^IRX"].dropna()
    rf = float(rate.iloc[-1]) / 100.0
    r_date = str(rate.index[-1].date())
    s0 = float(px.iloc[-1])
    K = float(round(s0 / 5) * 5)  # nearest listed 5-dollar strike
    sigma = vol_last

    call = float(bs_price(s0, K, T_YEARS, rf, sigma, "call"))
    put = float(bs_price(s0, K, T_YEARS, rf, sigma, "put"))
    greeks = {k: float(v) for k, v in bs_greeks(s0, K, T_YEARS, rf, sigma).items()}
    parity_gap = float(abs((call - put) - (s0 - K * np.exp(-rf * T_YEARS))))

    # --- 3 - the price curve C(S) vs intrinsic ------------------------------
    s_grid = np.linspace(0.6 * K, 1.4 * K, 81)
    c_curve = bs_price(s_grid, K, T_YEARS, rf, sigma, "call")
    intrinsic = np.maximum(s_grid - K, 0.0)

    # --- 4 - a smile the flat-sigma model cannot make -----------------------
    # Two-state Gaussian mixture on QQQ daily returns (seeded): a calm regime
    # and a stress regime. Under the risk-neutral mixture of lognormals the
    # call is a weight-average of BS prices; inverting each strike back
    # through BS produces a genuine smile from real-return calibration.
    gm = GaussianMixture(n_components=2, random_state=SEED, n_init=5)
    gm.fit(logret.values.reshape(-1, 1))
    w = gm.weights_.ravel()
    sig_d = np.sqrt(gm.covariances_.ravel())
    order = np.argsort(sig_d)
    w, sig_d = w[order], sig_d[order]
    sig_a = sig_d * np.sqrt(252)
    sigma_blend = float(np.sqrt(np.sum(w * sig_a**2)))

    def mix_call(strike: float) -> float:
        return float(sum(wi * bs_price(s0, strike, T_YEARS, rf, si, "call")
                         for wi, si in zip(w, sig_a)))

    m_grid = np.linspace(0.70, 1.30, 41)
    iv = []
    for m in m_grid:
        strike = m * s0
        price = mix_call(strike)
        iv.append(brentq(lambda v: bs_price(s0, strike, T_YEARS, rf, v, "call") - price,
                         1e-4, 3.0, xtol=1e-10))
    iv = np.array(iv)
    iv_at = {m: float(np.interp(m, m_grid, iv)) for m in (0.85, 1.00, 1.15)}

    # --- 5 - why: real returns are not lognormal ----------------------------
    kurt = float(stats.kurtosis(logret, fisher=True))
    skew = float(stats.skew(logret))
    worst = float(logret.min())
    worst_date = str(logret.idxmin().date())
    worst_sigmas = float(abs(worst) / logret.std(ddof=1))

    payload = {
        "params": {
            "start": str(px.index[0].date()), "end": str(px.index[-1].date()),
            "nObs": int(len(logret)), "s0": r(s0, 2), "K": r(K, 0),
            "T": T_YEARS, "r": r(rf), "rDate": r_date, "sigma": r(sigma),
            "seed": SEED,
        },
        "vol": {
            "roll252": downsample(roll252.values, 260),
            "xLabels": [[f, l] for f, l in year_labels(roll252.index, 1)],
            "min": r(vol_min), "max": r(vol_max), "last": r(vol_last),
            "max21": r(vol21_max), "max21Date": vol21_max_date,
        },
        "contract": {
            "call": r(call, 2), "put": r(put, 2), "parityGap": r(parity_gap, 10),
            "delta": r(greeks["delta"]), "gamma": r(greeks["gamma"], 5),
            "vega": r(greeks["vega"], 3), "theta": r(greeks["theta"], 4),
            "rho": r(greeks["rho"], 3),
        },
        "curve": {
            "s": r(list(s_grid), 1),
            "call": r(list(c_curve), 2),
            "intrinsic": r(list(intrinsic), 2),
            "kFrac": r(float((K - s_grid[0]) / (s_grid[-1] - s_grid[0]))),
        },
        "smile": {
            "m": r(list(m_grid), 3),
            "ivPct": r(list(iv * 100), 2),
            "flatPct": r(sigma_blend * 100, 2),
            "w": r(list(w)), "sigA": r(list(sig_a)),
            "iv85": r(iv_at[0.85] * 100, 1), "iv100": r(iv_at[1.00] * 100, 1),
            "iv115": r(iv_at[1.15] * 100, 1),
        },
        "reality": {
            "excessKurtosis": r(kurt, 2), "skew": r(skew, 2),
            "worstDay": r(worst, 4), "worstDate": worst_date,
            "worstSigmas": r(worst_sigmas, 1),
        },
    }
    ts = write_ts(SLUG, payload)

    # ------------------------------------------------------------ notebook --
    cells = [
        md(f"""# Black–Scholes from first principles

**pyportfolios.com** · [/research/black-scholes-from-first-principles](https://pyportfolios.com/research/black-scholes-from-first-principles) · QQQ 2017–2024 · NumPy · Pandas · SciPy · scikit-learn · yfinance

Black–Scholes is the answer to one question: *what must an option cost if you could
hedge it perfectly?* In this notebook we make every number in that answer real:

1. test the model's "constant σ" assumption against QQQ's rolling realised vol,
2. price a real ATM 1-year QQQ call — spot, vol and risk-free rate all observed,
3. compute all five Greeks and verify put–call parity,
4. draw the call price curve against intrinsic value, and
5. build the volatility smile the flat-σ model cannot make, from a 2-state
   mixture calibrated to QQQ's actual returns (seed {SEED})."""),
        code("""import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from scipy import stats
from scipy.optimize import brentq
from scipy.stats import norm
from sklearn.mixture import GaussianMixture

plt.rcParams["figure.figsize"] = (10, 5)
SEED = 42"""),
        md("""## 1 · Is σ constant? Ask the data

The model assumes one volatility, forever. QQQ's rolling 1-year realised vol is the
cheapest possible test of that assumption — download the closes, roll a standard
deviation, annualise."""),
        code("""px = yf.download("QQQ", start="2017-01-01", end="2025-01-01",
                 auto_adjust=True, progress=False)["Close"].squeeze().dropna()
logret = np.log(px / px.shift(1)).dropna()

roll252 = (logret.rolling(252).std(ddof=1) * np.sqrt(252)).dropna()
roll252.plot(title="QQQ trailing 1y realised volatility (annualised)")
plt.ylabel("sigma");

print(f"realised 1y vol: min {roll252.min():.1%}  max {roll252.max():.1%}  "
      f"latest {roll252.iloc[-1]:.1%}")"""),
        md("""So the "constant" parameter roughly tripled inside one sample. Keep that in mind —
it is exactly the crack the smile (section 5) grows out of.

## 2 · A real contract

We price a 1-year at-the-money call on QQQ using only observed inputs: the last
close as spot, the nearest listed strike, trailing 1y realised vol as σ, and the
13-week T-bill yield (^IRX, quoted in percent) as the risk-free rate."""),
        code("""irx = yf.download("^IRX", start="2024-12-01", end="2025-01-01",
                  auto_adjust=True, progress=False)["Close"].squeeze().dropna()

S0    = float(px.iloc[-1])
K     = round(S0 / 5) * 5          # nearest $5 strike
T     = 1.0
r     = float(irx.iloc[-1]) / 100  # ^IRX is in percent
sigma = float(roll252.iloc[-1])

print(f"S0 = {S0:.2f}   K = {K:.0f}   T = {T}   r = {r:.4f}   sigma = {sigma:.4f}")"""),
        md("""## 3 · Price and Greeks

Direct transcription of the closed form. The Greeks are the analytic derivatives of
the price, so they come almost for free."""),
        code("""def bs_price(S, K, T, r, sigma, kind="call"):
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    if kind == "call":
        return S * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)
    return K * np.exp(-r * T) * norm.cdf(-d2) - S * norm.cdf(-d1)

def bs_greeks(S, K, T, r, sigma):
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    pdf = norm.pdf(d1)
    return {
        "delta": norm.cdf(d1),
        "gamma": pdf / (S * sigma * np.sqrt(T)),
        "vega":  S * pdf * np.sqrt(T) / 100,
        "theta": (-(S * pdf * sigma) / (2 * np.sqrt(T))
                  - r * K * np.exp(-r * T) * norm.cdf(d2)) / 365,
        "rho":   K * T * np.exp(-r * T) * norm.cdf(d2) / 100,
    }

C = bs_price(S0, K, T, r, sigma, "call")
P = bs_price(S0, K, T, r, sigma, "put")
print(f"call = {C:.2f}   put = {P:.2f}")
for k, v in bs_greeks(S0, K, T, r, sigma).items():
    print(f"{k:>6}: {v: .4f}")

# put-call parity: C - P = S - K e^{-rT}, to machine precision
assert abs((C - P) - (S0 - K * np.exp(-r * T))) < 1e-8"""),
        md("""## 4 · The price curve

Plot C(S) across spot against the hockey-stick intrinsic value. The vertical gap
between the two is time value; delta is the slope of the smooth curve."""),
        code("""s_grid = np.linspace(0.6 * K, 1.4 * K, 81)
plt.plot(s_grid, bs_price(s_grid, K, T, r, sigma), lw=2, label="BS call C(S)")
plt.plot(s_grid, np.maximum(s_grid - K, 0), "--", lw=1.5, color="grey",
         label="intrinsic max(S-K, 0)")
plt.axvline(K, color="k", lw=0.6)
plt.xlabel("spot S"); plt.ylabel("call value")
plt.title(f"1y call, K={K:.0f} — price vs intrinsic"); plt.legend();"""),
        md("""## 5 · The smile the model cannot make

If volatility really were one number, every strike would imply the same σ. But QQQ's
returns are not one lognormal — a 2-state Gaussian mixture (calm + stress) fits them
far better. Price calls under that mixture (a weight-average of BS prices is exact
for a mixture of lognormals), then invert each price back through Black–Scholes:
the implied σ is no longer flat. That U-shape is the smile, generated here entirely
from real-return calibration."""),
        code("""gm = GaussianMixture(n_components=2, random_state=SEED, n_init=5)
gm.fit(logret.values.reshape(-1, 1))
w     = gm.weights_.ravel()
sig_d = np.sqrt(gm.covariances_.ravel())
order = np.argsort(sig_d)
w, sig_a = w[order], sig_d[order] * np.sqrt(252)

print(f"calm  : weight {w[0]:.2f}, sigma {sig_a[0]:.1%}")
print(f"stress: weight {w[1]:.2f}, sigma {sig_a[1]:.1%}")
print(f"excess kurtosis of QQQ returns: {stats.kurtosis(logret):.2f} (normal = 0)")

def mix_call(strike):
    return sum(wi * bs_price(S0, strike, T, r, si) for wi, si in zip(w, sig_a))

m_grid = np.linspace(0.70, 1.30, 41)
iv = [brentq(lambda v: bs_price(S0, m * S0, T, r, v) - mix_call(m * S0), 1e-4, 3.0)
      for m in m_grid]

blend = np.sqrt(np.sum(w * sig_a**2))
plt.plot(m_grid, np.array(iv) * 100, lw=2, label="mixture-implied vol")
plt.axhline(blend * 100, ls="--", color="grey", label="flat BS sigma")
plt.xlabel("moneyness K / S"); plt.ylabel("implied vol (%)")
plt.title("Implied volatility by strike — the smile"); plt.legend();"""),
        md("""## Takeaways

- Every input to Black–Scholes is observable except σ — and σ is the one the data
  refuses to hold constant.
- Price, all five Greeks, and put–call parity: ~20 lines of NumPy.
- Two vol regimes are enough to bend the flat line into a smile. Real markets have
  more than two, which is why real smiles are steeper still — especially the put wing.
- The formula survives its own falsification by becoming a *quoting convention*:
  traders quote implied vol precisely because BS is an invertible translation.

*© pyportfolios.com — runnable companion to the article. Data: Yahoo Finance via yfinance.*"""),
    ]
    nb_path = write_nb(SLUG, cells)

    print(f"ts  -> {ts}")
    print(f"nb  -> {nb_path}")
    print(f"S0={s0:.2f} K={K:.0f} r={rf:.4f} sigma={sigma:.4f} call={call:.2f} put={put:.2f}")
    print(f"greeks={ {k: round(v, 4) for k, v in greeks.items()} }")
    print(f"vol range 1y: {vol_min:.4f}..{vol_max:.4f}  mixture w={w.round(3)} sig={sig_a.round(4)}")
    print(f"smile iv85={iv_at[0.85]:.4f} iv100={iv_at[1.00]:.4f} iv115={iv_at[1.15]:.4f} blend={sigma_blend:.4f}")
    print(f"kurt={kurt:.2f} worst={worst:.4f} ({worst_date}, {worst_sigmas:.1f} sigma)")


if __name__ == "__main__":
    main()
