"""
Legacy upgrade - Ledoit-Wolf shrinkage, from scratch (portfolio-optimization).
Assets: the 11 SPDR sector ETFs (XLB XLC XLE XLF XLI XLK XLP XLRE XLU XLV XLY),
daily returns from the first date all 11 trade (mid-2018, XLC inception) through
Dec 2024. Libs: NumPy Pandas scikit-learn.

Replaces the illustrative OOS-volatility squiggle + made-up table with real
computed results:
  - conditioning of the sample covariance on a short window (N=11, T=60),
  - eigenvalue spectra, sample vs shrunk, and the analytic intensity delta,
  - a from-scratch estimator cross-checked against sklearn.covariance.LedoitWolf,
  - a rolling out-of-sample min-variance backtest (60d window, 21d holding):
    realised vol, max weight, turnover - sample vs Ledoit-Wolf.

Data: reuses quant/data/rn16_sectors.csv (shared cache). If it were missing this
script would re-download it via yfinance into
quant/data/legacy_ledoit-wolf-shrinkage.csv. Deterministic (no randomness).
Emits the article data module + the runnable notebook (vault/notebooks).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yfinance as yf
from sklearn.covariance import LedoitWolf

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from emit import DATA, TS_OUT, code, downsample, load, md, r, write_nb, year_labels  # noqa: E402

SLUG = "ledoit-wolf-shrinkage"
SECTORS = ["XLB", "XLC", "XLE", "XLF", "XLI", "XLK", "XLP", "XLRE", "XLU", "XLV", "XLY"]
WINDOW = 60     # estimation window (T) - deliberately short vs N=11
HOLD = 21       # holding period between rebalances


def write_ts(slug: str, payload: dict) -> Path:
    """Local variant of emit.write_ts with the correct rebuild path."""
    TS_OUT.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, indent=2, allow_nan=False)
    src = (
        "/* GENERATED by quant pipeline — do not hand-edit.\n"
        "   Rebuild: python quant/legacy/ledoit_wolf.py\n"
        "   Real computed results; charts render these via DataCharts.tsx. */\n\n"
        f"const data = {body} as const;\n\nexport default data;\n"
    )
    out = TS_OUT / f"{slug}.ts"
    out.write_text(src, encoding="utf-8")
    return out


def load_sectors() -> pd.DataFrame:
    """Prefer the shared rn16 cache; self-cache a legacy copy if it is absent."""
    if (DATA / "rn16_sectors.csv").exists():
        return load("rn16_sectors")
    out = DATA / f"legacy_{SLUG}.csv"
    if not out.exists():
        df = yf.download(SECTORS, start="2018-01-01", end="2025-01-01",
                         auto_adjust=True, progress=False)["Close"]
        df.dropna(how="all").to_csv(out)
    return load(f"legacy_{SLUG}")


# ----------------------------------------------------------- the estimator --

def ledoit_wolf(X: np.ndarray):
    """X: (T, N) returns, rows = observations. Returns (shrunk_cov, delta)."""
    T, N = X.shape
    X = X - X.mean(axis=0)
    S = X.T @ X / T                       # sample covariance (MLE)
    mu = np.trace(S) / N                  # average variance
    F = mu * np.eye(N)                    # spherical target

    d2 = ((S - F) ** 2).sum() / N         # distance from target
    X2 = X ** 2
    b2 = ((X2.T @ X2) / T - S ** 2).sum() / (N * T)   # noise in S
    b2 = min(b2, d2)                      # bound: never shrink past the target
    delta = b2 / d2 if d2 > 0 else 0.0    # optimal intensity, already in [0, 1]

    return (1 - delta) * S + delta * F, delta


def min_var(cov: np.ndarray) -> np.ndarray:
    w = np.linalg.solve(cov, np.ones(cov.shape[0]))
    return w / w.sum()


def main() -> None:
    px = load_sectors()[SECTORS].dropna()          # all 11 present (XLC from 2018-06)
    rets = px.pct_change().dropna()
    dates = rets.index

    # --- 1 - conditioning on one short window (the demo estimate) ----------
    Xd = rets.iloc[-WINDOW:].to_numpy()
    Xc = Xd - Xd.mean(axis=0)
    S = Xc.T @ Xc / WINDOW
    LW_cov, delta_demo = ledoit_wolf(Xd)

    eig_s = np.sort(np.linalg.eigvalsh(S))[::-1]
    eig_lw = np.sort(np.linalg.eigvalsh(LW_cov))[::-1]
    cond_s = float(eig_s[0] / eig_s[-1])
    cond_lw = float(eig_lw[0] / eig_lw[-1])
    mu_target = float(np.trace(S) / len(SECTORS))

    # cross-check against scikit-learn (uses the same MLE + spherical target)
    skl = LedoitWolf(assume_centered=False).fit(Xd)
    max_diff = float(np.abs(skl.covariance_ - LW_cov).max())
    delta_skl = float(skl.shrinkage_)

    # eigen-direction volatilities (annualised, %) for the spectrum chart
    spec_s = [float(np.sqrt(v * 252) * 100) for v in eig_s]
    spec_lw = [float(np.sqrt(v * 252) * 100) for v in eig_lw]

    # --- 2 - rolling out-of-sample min-variance backtest --------------------
    oos: dict[str, list] = {"sample": [], "lw": []}
    oos_idx: list = []
    max_w = {"sample": 0.0, "lw": 0.0}
    turno = {"sample": [], "lw": []}
    prev_w = {"sample": None, "lw": None}
    deltas = []

    starts = range(WINDOW, len(rets) - 1, HOLD)
    for i in starts:
        Xw = rets.iloc[i - WINDOW:i].to_numpy()
        Xcw = Xw - Xw.mean(axis=0)
        S_w = Xcw.T @ Xcw / WINDOW
        LW_w, d_w = ledoit_wolf(Xw)
        deltas.append(d_w)
        seg = rets.iloc[i:i + HOLD].to_numpy()
        seg_idx = dates[i:i + HOLD]
        for name, cov in (("sample", S_w), ("lw", LW_w)):
            w = min_var(cov)
            max_w[name] = max(max_w[name], float(np.abs(w).max()))
            if prev_w[name] is not None:
                turno[name].append(float(np.abs(w - prev_w[name]).sum()))
            prev_w[name] = w
            oos[name].extend(list(seg @ w))
        oos_idx.extend(list(seg_idx))

    oos_s = pd.Series(oos["sample"], index=oos_idx)
    oos_l = pd.Series(oos["lw"], index=oos_idx)
    vol_s = float(oos_s.std(ddof=1) * np.sqrt(252))
    vol_l = float(oos_l.std(ddof=1) * np.sqrt(252))
    roll_s = (oos_s.rolling(63).std(ddof=1) * np.sqrt(252)).dropna()
    roll_l = (oos_l.rolling(63).std(ddof=1) * np.sqrt(252)).dropna()
    turn_s = float(np.mean(turno["sample"]))
    turn_l = float(np.mean(turno["lw"]))
    n_reb = len(deltas)
    d_min, d_max, d_mean = float(np.min(deltas)), float(np.max(deltas)), float(np.mean(deltas))

    payload = {
        "params": {
            "sectors": SECTORS, "n": len(SECTORS),
            "start": str(rets.index[0].date()), "end": str(rets.index[-1].date()),
            "nObs": int(len(rets)), "window": WINDOW, "hold": HOLD,
            "nRebalances": n_reb,
        },
        "demo": {
            "delta": r(delta_demo), "deltaSklearn": r(delta_skl),
            "maxDiffSklearn": r(max_diff, 12),
            "condSample": r(cond_s, 1), "condLW": r(cond_lw, 1),
            "muTargetAnnVolPct": r(float(np.sqrt(mu_target * 252) * 100), 1),
            "eigLabels": [f"λ{i + 1}" for i in range(len(SECTORS))],
            "specSample": r(spec_s, 2), "specLW": r(spec_lw, 2),
        },
        "backtest": {
            "volSample": r(vol_s), "volLW": r(vol_l),
            "maxWSample": r(max_w["sample"]), "maxWLW": r(max_w["lw"]),
            "turnSample": r(turn_s), "turnLW": r(turn_l),
            "deltaMin": r(d_min), "deltaMax": r(d_max), "deltaMean": r(d_mean),
            "rollSample": downsample(roll_s.values * 100, 240),
            "rollLW": downsample(roll_l.values * 100, 240),
            "xLabels": [[f, l] for f, l in year_labels(roll_s.index, 1)],
        },
    }
    ts = write_ts(SLUG, payload)

    # ------------------------------------------------------------ notebook --
    cells = [
        md("""# Ledoit–Wolf shrinkage, from scratch

**pyportfolios.com** · [/research/ledoit-wolf-shrinkage](https://pyportfolios.com/research/ledoit-wolf-shrinkage) · 11 SPDR sector ETFs, 2018–2024 · NumPy · Pandas · scikit-learn · yfinance

The sample covariance matrix is an error-maximiser in disguise: the mean–variance
optimiser pours weight into exactly the directions it has estimated worst. In this
notebook we

1. measure how badly conditioned the sample covariance of the 11 sector ETFs is
   on a short window (T=60, N=11),
2. build the Ledoit–Wolf estimator from scratch and cross-check it against
   `sklearn.covariance.LedoitWolf` to machine precision,
3. watch shrinkage lift the small eigenvalues (the ones inversion amplifies), and
4. run the honest test: a rolling out-of-sample minimum-variance backtest,
   sample vs shrunk."""),
        code("""import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from sklearn.covariance import LedoitWolf

plt.rcParams["figure.figsize"] = (10, 5)"""),
        md("""## 1 · Data: the 11 sector SPDRs

One ETF per GICS sector. XLC only exists since June 2018, so the balanced panel
runs from there — about 1,600 trading days of 11 daily return series."""),
        code("""SECTORS = ["XLB", "XLC", "XLE", "XLF", "XLI", "XLK", "XLP", "XLRE", "XLU", "XLV", "XLY"]

px = yf.download(SECTORS, start="2018-01-01", end="2025-01-01",
                 auto_adjust=True, progress=False)["Close"][SECTORS].dropna()
rets = px.pct_change().dropna()
print(f"{rets.shape[0]} days x {rets.shape[1]} assets, {rets.index[0].date()} .. {rets.index[-1].date()}")"""),
        md("""## 2 · The estimator, from scratch

Shrink the sample matrix toward the spherical target F = μ·I (μ = average sample
variance) with the analytic intensity δ* = b²/d² — noise over distance-from-target.
No cross-validation, no tuning."""),
        code("""def ledoit_wolf(X):
    \"\"\"X: (T, N) returns, rows = observations. Returns (shrunk_cov, delta).\"\"\"
    T, N = X.shape
    X = X - X.mean(axis=0)
    S = X.T @ X / T                       # sample covariance (MLE)
    mu = np.trace(S) / N                  # average variance
    F = mu * np.eye(N)                    # spherical target

    d2 = ((S - F) ** 2).sum() / N         # distance from target
    X2 = X ** 2
    b2 = ((X2.T @ X2) / T - S ** 2).sum() / (N * T)   # noise in S
    b2 = min(b2, d2)                      # never shrink past the target
    delta = b2 / d2 if d2 > 0 else 0.0

    return (1 - delta) * S + delta * F, delta"""),
        md("""## 3 · Conditioning, and the sklearn cross-check

Estimate on the last 60 trading days only — 11 assets from 60 observations, the
regime where the sample matrix is at its most treacherous. Then verify our twelve
lines against scikit-learn."""),
        code("""X = rets.iloc[-60:].to_numpy()

Xc = X - X.mean(axis=0)
S  = Xc.T @ Xc / len(X)
LW_cov, delta = ledoit_wolf(X)

skl = LedoitWolf().fit(X)
print(f"delta (ours)    : {delta:.4f}")
print(f"delta (sklearn) : {skl.shrinkage_:.4f}")
print(f"max |diff| vs sklearn covariance: {np.abs(skl.covariance_ - LW_cov).max():.2e}")

eig_s  = np.sort(np.linalg.eigvalsh(S))[::-1]
eig_lw = np.sort(np.linalg.eigvalsh(LW_cov))[::-1]
print(f"\\ncondition number: sample {eig_s[0]/eig_s[-1]:,.0f}  ->  shrunk {eig_lw[0]/eig_lw[-1]:,.0f}")

x = np.arange(1, 12)
plt.bar(x - 0.2, np.sqrt(eig_s  * 252) * 100, 0.4, label="sample")
plt.bar(x + 0.2, np.sqrt(eig_lw * 252) * 100, 0.4, label="ledoit-wolf")
plt.xticks(x, [f"$\\\\lambda_{{{i}}}$" for i in x])
plt.ylabel("eigen-direction vol (% ann.)")
plt.title("Eigenvalue spectrum — shrinkage lifts the noisy floor"); plt.legend();"""),
        md("""Inversion divides by the *smallest* eigenvalues. Shrinkage barely touches the top of
the spectrum (the market factor) but lifts the floor — exactly the directions the
optimiser would otherwise bet on hardest.

## 4 · The out-of-sample test

Minimum-variance weights w ∝ Σ⁻¹·1, re-estimated every 21 trading days on the
trailing 60-day window, held forward. Same data, same rebalance dates — the only
difference is the covariance estimator."""),
        code("""def min_var(cov):
    w = np.linalg.solve(cov, np.ones(cov.shape[0]))
    return w / w.sum()

WINDOW, HOLD = 60, 21
oos = {"sample": [], "ledoit-wolf": []}
idx, max_w, turn, prev = [], {k: 0.0 for k in oos}, {k: [] for k in oos}, {k: None for k in oos}

for i in range(WINDOW, len(rets) - 1, HOLD):
    Xw = rets.iloc[i - WINDOW:i].to_numpy()
    Xc = Xw - Xw.mean(axis=0)
    covs = {"sample": Xc.T @ Xc / WINDOW, "ledoit-wolf": ledoit_wolf(Xw)[0]}
    seg = rets.iloc[i:i + HOLD].to_numpy()
    idx.extend(rets.index[i:i + HOLD])
    for name, cov in covs.items():
        w = min_var(cov)
        max_w[name] = max(max_w[name], np.abs(w).max())
        if prev[name] is not None:
            turn[name].append(np.abs(w - prev[name]).sum())
        prev[name] = w
        oos[name].extend(seg @ w)

for name in oos:
    s = pd.Series(oos[name], index=idx)
    print(f"{name:>12}: OOS vol {s.std(ddof=1) * np.sqrt(252):6.2%}   "
          f"max |w| {max_w[name]:5.1%}   avg turnover {np.mean(turn[name]):.2f}/rebalance")"""),
        md("""## 5 · Rolling realised risk

The same result through time: rolling 63-day annualised volatility of the two
out-of-sample return streams."""),
        code("""roll = pd.DataFrame({k: pd.Series(v, index=idx) for k, v in oos.items()})
(roll.rolling(63).std(ddof=1) * np.sqrt(252) * 100).dropna().plot(
    title="Rolling 63d out-of-sample volatility, min-variance portfolios (%)")
plt.ylabel("annualised vol (%)");"""),
        md("""## Takeaways

- With N=11 and T=60 the sample covariance is genuinely ill-conditioned; inversion
  amplifies its noisiest directions and the optimiser bets on them.
- The whole fix is twelve lines, and δ is analytic — the data tells you how much
  to trust it. Our from-scratch estimator matches sklearn to machine precision.
- Out of sample, shrinkage delivers lower realised vol, saner max weights and less
  turnover — a free lunch paid for by accepting a little bias.
- Reach for Ledoit–Wolf by default whenever N is comparable to T.

*© pyportfolios.com — runnable companion to the article. Data: Yahoo Finance via yfinance.*"""),
    ]
    nb_path = write_nb(SLUG, cells)

    print(f"ts  -> {ts}")
    print(f"nb  -> {nb_path}")
    print(f"panel {len(rets)}d x {len(SECTORS)}  window={WINDOW} hold={HOLD} rebalances={n_reb}")
    print(f"demo delta={delta_demo:.4f} (skl {delta_skl:.4f}, maxdiff {max_diff:.2e}) "
          f"cond {cond_s:,.1f} -> {cond_lw:,.1f}")
    print(f"OOS vol: sample={vol_s:.4f} lw={vol_l:.4f}  maxw: {max_w['sample']:.3f}/{max_w['lw']:.3f}  "
          f"turnover: {turn_s:.3f}/{turn_l:.3f}")
    print(f"delta over windows: min={d_min:.3f} mean={d_mean:.3f} max={d_max:.3f}")


if __name__ == "__main__":
    main()
