"""
Legacy upgrade - The time value of money, in code (finance-fundamentals).
Assets: US Treasury yields ^IRX (13w) ^FVX (5y) ^TNX (10y) ^TYX (30y),
Dec 2021 - Jan 2023 (the 2022 tightening cycle). Libs: NumPy Pandas yfinance.

Replaces the hand-drawn discount-factor decay + made-up zero curve with real
computed results:
  - the four Treasury yields through 2022 (rates going from ~0 to ~4.4%),
  - discount curves DF(t) built from the observed start- and end-of-2022 zeros,
  - present-value and compounding-convention examples at the real 10y yield,
  - a 5% coupon bond priced off both real curves (the duration teaser).

Data: reuses quant/data/t03_bonds_yields.csv (shared cache; ^TNX 1.434 == 1.434%).
If it were missing this script would re-download it via yfinance into
quant/data/legacy_time-value-of-money.csv. Deterministic (no randomness).
Emits the article data module + the runnable notebook (vault/notebooks).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yfinance as yf

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from emit import DATA, TS_OUT, code, downsample, load, md, r, write_nb  # noqa: E402

SLUG = "time-value-of-money"
TICKERS = ["^IRX", "^FVX", "^TNX", "^TYX"]
MATS = [0.25, 5.0, 10.0, 30.0]
LABELS = ["3m", "5y", "10y", "30y"]
JAN, DEC = "2022-01-03", "2022-12-30"


def write_ts(slug: str, payload: dict) -> Path:
    """Local variant of emit.write_ts with the correct rebuild path."""
    TS_OUT.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, indent=2, allow_nan=False)
    src = (
        "/* GENERATED by quant pipeline — do not hand-edit.\n"
        "   Rebuild: python quant/legacy/tvm.py\n"
        "   Real computed results; charts render these via DataCharts.tsx. */\n\n"
        f"const data = {body} as const;\n\nexport default data;\n"
    )
    out = TS_OUT / f"{slug}.ts"
    out.write_text(src, encoding="utf-8")
    return out


def load_yields() -> pd.DataFrame:
    """Prefer the shared t03 cache; self-cache a legacy copy if it is absent."""
    if (DATA / "t03_bonds_yields.csv").exists():
        return load("t03_bonds_yields")
    out = DATA / f"legacy_{SLUG}.csv"
    if not out.exists():
        df = yf.download(TICKERS, start="2021-12-01", end="2023-01-10",
                         auto_adjust=True, progress=False)["Close"]
        df.dropna(how="all").to_csv(out)
    return load(f"legacy_{SLUG}")


def zero_curve(yields_pct: np.ndarray):
    """Continuously-compounded zero curve, linearly interpolated in yield."""
    y_dec = np.asarray(yields_pct, dtype=float) / 100.0

    def y(t):
        return np.interp(t, MATS, y_dec)

    return y


def main() -> None:
    ylds = load_yields()[TICKERS].dropna()

    jan = ylds.loc[JAN].astype(float)   # percent
    dec = ylds.loc[DEC].astype(float)
    y_jan, y_dec = zero_curve(jan.values), zero_curve(dec.values)

    # --- 1 - the 2022 repricing of time itself ------------------------------
    hist = {t: downsample(ylds[t].values, 130) for t in TICKERS}
    n = len(ylds)
    month_marks = []
    for stamp in ("2022-01-01", "2022-04-01", "2022-07-01", "2022-10-01", "2023-01-01"):
        pos = ylds.index.searchsorted(pd.Timestamp(stamp))
        if 0 <= pos < n:
            month_marks.append([round(pos / (n - 1), 4), pd.Timestamp(stamp).strftime("%b %y")])

    # --- 2 - discount curves DF(t) = exp(-y(t) t) ---------------------------
    t_grid = np.linspace(0.0, 30.0, 121)
    df_jan = np.exp(-y_jan(np.maximum(t_grid, 0.25)) * t_grid)
    df_dec = np.exp(-y_dec(np.maximum(t_grid, 0.25)) * t_grid)

    # --- 3 - present value: $100 in 10 years, both curves -------------------
    y10_jan, y10_dec = float(y_jan(10)), float(y_dec(10))
    pv_jan = 100 * np.exp(-y10_jan * 10)
    pv_dec = 100 * np.exp(-y10_dec * 10)

    # --- 4 - compounding conventions at the real 10y rate -------------------
    conv = {
        "rate": y10_dec,
        "annual": (1 + y10_dec) ** -10,
        "semi": (1 + y10_dec / 2) ** -20,
        "monthly": (1 + y10_dec / 12) ** -120,
        "continuous": np.exp(-y10_dec * 10),
    }

    # --- 5 - the 5% coupon bond off both real curves -------------------------
    times = np.arange(1, 6, dtype=float)
    flows = np.array([5, 5, 5, 5, 105], dtype=float)

    def price_rows(y_fn):
        zr = y_fn(times)
        dfs = np.exp(-zr * times)
        pvs = flows * dfs
        return zr, dfs, pvs, float(pvs.sum())

    zr_dec, dfs_dec, pvs_dec, price_dec = price_rows(y_dec)
    _, _, _, price_jan = price_rows(y_jan)

    payload = {
        "params": {
            "start": str(ylds.index[0].date()), "end": str(ylds.index[-1].date()),
            "nObs": int(n), "tickers": TICKERS, "labels": LABELS, "mats": MATS,
            "janDate": JAN, "decDate": DEC,
        },
        "history": {
            "irx": hist["^IRX"], "fvx": hist["^FVX"],
            "tnx": hist["^TNX"], "tyx": hist["^TYX"],
            "xLabels": month_marks,
            "irxStart": r(float(jan["^IRX"]), 2), "irxEnd": r(float(dec["^IRX"]), 2),
        },
        "curves": {
            "jan": r(list(jan.values), 2), "dec": r(list(dec.values), 2),
            "tGrid": r(list(t_grid), 2),
            "dfJan": r(list(df_jan)), "dfDec": r(list(df_dec)),
            "dfJan30": r(float(df_jan[-1])), "dfDec30": r(float(df_dec[-1])),
        },
        "pv": {
            "y10Jan": r(y10_jan), "y10Dec": r(y10_dec),
            "pvJan": r(float(pv_jan), 2), "pvDec": r(float(pv_dec), 2),
        },
        "compounding": {
            "ratePct": r(conv["rate"] * 100, 2),
            "annual": r(float(conv["annual"])), "semi": r(float(conv["semi"])),
            "monthly": r(float(conv["monthly"])), "continuous": r(float(conv["continuous"])),
        },
        "bond": {
            "times": r(list(times), 0), "flows": r(list(flows), 0),
            "zeroPct": r(list(zr_dec * 100), 2),
            "df": r(list(dfs_dec)), "pv": r(list(pvs_dec), 2),
            "priceDec": r(price_dec, 2), "priceJan": r(price_jan, 2),
        },
    }
    ts = write_ts(SLUG, payload)

    # ------------------------------------------------------------ notebook --
    cells = [
        md("""# The time value of money, in code

**pyportfolios.com** · [/research/time-value-of-money](https://pyportfolios.com/research/time-value-of-money) · US Treasury yields, Dec 2021 – Jan 2023 · NumPy · Pandas · yfinance

Every valuation is the same gesture: take cash arriving later, ask what it is worth
now. In this notebook we do it with *real* rates — the US Treasury curve straight
off Yahoo Finance, through the most violent repricing of money in four decades
(calendar 2022). We

1. download the 13-week, 5y, 10y and 30y Treasury yields,
2. watch the price of time explode through 2022,
3. build discount curves DF(t) from the observed zeros,
4. compare compounding conventions at the real 10y rate, and
5. price a 5% coupon bond off both curves — and see rate risk fall out."""),
        code("""import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

plt.rcParams["figure.figsize"] = (10, 5)"""),
        md("""## 1 · Real rates, from the tape

Yahoo's Treasury yield indices are quoted in percent (^TNX = 3.88 means 3.88%).
Four points on the curve: 13 weeks, 5, 10 and 30 years."""),
        code("""TICKERS = ["^IRX", "^FVX", "^TNX", "^TYX"]   # 13w, 5y, 10y, 30y
MATS    = [0.25, 5, 10, 30]

ylds = yf.download(TICKERS, start="2021-12-01", end="2023-01-10",
                   auto_adjust=True, progress=False)["Close"][TICKERS].dropna()

ylds.plot(title="US Treasury yields through 2022 (percent)")
plt.ylabel("yield (%)");

jan = ylds.loc["2022-01-03"]
dec = ylds.loc["2022-12-30"]
print(pd.DataFrame({"3 Jan 2022": jan.values, "30 Dec 2022": dec.values},
                   index=["3m", "5y", "10y", "30y"]).round(2))"""),
        md("""The 13-week bill went from essentially free money to over 4% inside a year. Money
re-acquired its time stamp in 2022 — which makes it the perfect sample for this topic.

## 2 · From yields to a discount curve

A zero rate y(t) and continuous compounding give the discount factor
$DF(t) = e^{-y(t)\\,t}$ — the price, today, of one dollar delivered at t. We
interpolate the four observed zeros linearly in yield and draw DF(t) for both
ends of 2022."""),
        code("""def zero_curve(yields_pct):
    y_dec = np.asarray(yields_pct, dtype=float) / 100
    return lambda t: np.interp(t, MATS, y_dec)

y_jan, y_dec_ = zero_curve(jan.values), zero_curve(dec.values)

t = np.linspace(0, 30, 121)
plt.plot(t, np.exp(-y_jan(np.maximum(t, 0.25)) * t), lw=2, label="curve of 3 Jan 2022")
plt.plot(t, np.exp(-y_dec_(np.maximum(t, 0.25)) * t), lw=2, label="curve of 30 Dec 2022")
plt.xlabel("maturity t (years)"); plt.ylabel("DF(t)")
plt.title("Discount factor by maturity — one dollar, delivered later"); plt.legend();

print(f"DF(30y), Jan 2022: {np.exp(-y_jan(30) * 30):.4f}")
print(f"DF(30y), Dec 2022: {np.exp(-y_dec_(30) * 30):.4f}")"""),
        md("""## 3 · Present value, concretely

$100 arriving in 10 years, discounted at the observed 10y zero:"""),
        code("""for name, fn in [("Jan 2022", y_jan), ("Dec 2022", y_dec_)]:
    y10 = fn(10)
    print(f"{name}: 10y zero = {y10:.2%}  ->  PV of $100 in 10y = ${100 * np.exp(-y10 * 10):.2f}")"""),
        md("""## 4 · Compounding conventions

The same quoted rate means different things depending on how often it compounds.
At the real end-2022 10y rate, here is DF(10) under each convention — same
economics, different units:"""),
        code("""r10 = float(y_dec_(10))
print(f"10y zero rate: {r10:.4%}\\n")
for name, df in [("annual",     (1 + r10) ** -10),
                 ("semi-annual",(1 + r10 / 2) ** -20),
                 ("monthly",    (1 + r10 / 12) ** -120),
                 ("continuous", np.exp(-r10 * 10))]:
    print(f"{name:>12}: DF(10) = {df:.4f}")"""),
        md("""## 5 · Valuing a cashflow stream

Price a 5% annual-coupon bond (par 100, 5 years) off the real end-2022 curve.
The valuation is one line — flows dotted against discount factors."""),
        code("""cf = pd.DataFrame({"t": [1, 2, 3, 4, 5], "flow": [5, 5, 5, 5, 105]})

cf["rate"] = y_dec_(cf["t"].to_numpy(dtype=float))
cf["df"]   = np.exp(-cf["rate"] * cf["t"])
cf["pv"]   = cf["flow"] * cf["df"]
print(cf.round(4))
print(f"\\nBond price off the Dec 2022 curve: {cf['pv'].sum():,.2f}")

# same bond, one year earlier
cf["pv_jan"] = cf["flow"] * np.exp(-y_jan(cf["t"].to_numpy(dtype=float)) * cf["t"])
print(f"Bond price off the Jan 2022 curve: {cf['pv_jan'].sum():,.2f}")"""),
        md("""## Takeaways

- A discount factor is a *price* — of one dollar delivered later. Everything else
  (PV, bond prices, swap legs) is a dot product against those prices.
- Conventions change the arithmetic, not the economics: know which one a quote uses.
- The 2022 curve shift repriced the same five cashflows by several points of par.
  That sensitivity is duration — the next tutorial in the chain.

*© pyportfolios.com — runnable companion to the article. Data: Yahoo Finance via yfinance.*"""),
    ]
    nb_path = write_nb(SLUG, cells)

    print(f"ts  -> {ts}")
    print(f"nb  -> {nb_path}")
    print(f"jan curve: {list(jan.round(2))}  dec curve: {list(dec.round(2))}")
    print(f"DF30 jan={df_jan[-1]:.4f} dec={df_dec[-1]:.4f}")
    print(f"PV $100@10y: jan={pv_jan:.2f} (y={y10_jan:.4f})  dec={pv_dec:.2f} (y={y10_dec:.4f})")
    print(f"conv DF(10): annual={conv['annual']:.4f} semi={conv['semi']:.4f} "
          f"monthly={conv['monthly']:.4f} cont={conv['continuous']:.4f}")
    print(f"bond: dec={price_dec:.2f} jan={price_jan:.2f}  rows pv={pvs_dec.round(2)}")


if __name__ == "__main__":
    main()
