"""
emit.py - shared helpers for the tutorial pipeline.

Each tutorial script computes real results from the cached CSVs (quant/data/)
and emits:
  1. a TS data module   -> site/src/content/articles/data/<slug>.ts
  2. a runnable notebook -> site/public/notebooks/<slug>.ipynb

The TS module is consumed by the article body via the generic chart components
(site/src/components/charts/echarts/). Never hand-edit generated files.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "quant" / "data"
TS_OUT = REPO / "site" / "src" / "content" / "articles" / "data"
# Notebooks are the paid product: they live in vault/ (served through the
# gated platform API), NOT in site/public (which ships in the static export).
NB_OUT = REPO / "vault" / "notebooks"


def load(name: str) -> pd.DataFrame:
    df = pd.read_csv(DATA / f"{name}.csv", index_col=0, parse_dates=True)
    return df.sort_index()


def downsample(arr, n: int = 240) -> list[float]:
    """Evenly thin a series to <=n points, always keeping the last point."""
    a = np.asarray(arr, dtype=float)
    if len(a) <= n:
        return [round(float(v), 4) for v in a]
    idx = np.linspace(0, len(a) - 1, n).round().astype(int)
    return [round(float(v), 4) for v in a[idx]]


def r(v, nd: int = 4):
    """Round scalars / nested lists for compact TS output."""
    if isinstance(v, (list, tuple, np.ndarray)):
        return [r(x, nd) for x in v]
    if isinstance(v, (float, np.floating)):
        out = round(float(v), nd)
        return 0.0 if out == 0 else out
    if isinstance(v, (int, np.integer)):
        return int(v)
    return v


def year_labels(index: pd.DatetimeIndex, step: int = 2) -> list[tuple[float, str]]:
    """[fraction, 'YY] pairs for LineChart xLabels."""
    years = sorted({d.year for d in index})
    n = len(index)
    out: list[tuple[float, str]] = []
    for y in years[::step]:
        pos = index.searchsorted(pd.Timestamp(f"{y}-01-01"))
        if 0 <= pos < n:
            out.append((round(pos / max(n - 1, 1), 4), f"'{str(y)[2:]}"))
    return out


def write_ts(slug: str, payload: dict[str, Any]) -> Path:
    TS_OUT.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, indent=2, allow_nan=False)
    src = (
        "/* GENERATED by quant pipeline — do not hand-edit.\n"
        f"   Rebuild: python quant/tutorials/{slug.replace('-', '_')}.py\n"
        "   Real computed results; charts render these via DataCharts.tsx. */\n\n"
        f"const data = {body} as const;\n\nexport default data;\n"
    )
    out = TS_OUT / f"{slug}.ts"
    out.write_text(src, encoding="utf-8")
    return out


# ------------------------------------------------------------- notebooks --

def nb(cells: list[dict[str, Any]], kernel_display: str = "Python 3 (ipykernel)") -> dict[str, Any]:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": kernel_display, "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def md(source: str) -> dict[str, Any]:
    return {"cell_type": "markdown", "metadata": {}, "source": source.strip()}


def code(source: str) -> dict[str, Any]:
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": source.strip(),
    }


def write_nb(slug: str, cells: list[dict[str, Any]]) -> Path:
    NB_OUT.mkdir(parents=True, exist_ok=True)
    out = NB_OUT / f"{slug}.ipynb"
    out.write_text(json.dumps(nb(cells), indent=1, allow_nan=False), encoding="utf-8")
    return out
