"""
gen_category_pages.py - one static page per research category.

Next.js resolves static segments before dynamic ones, so
site/src/app/research/<category>/page.tsx wins over research/[slug] without
touching the article route. Category slugs and article slugs are disjoint
(asserted below), so nothing can shadow an article.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
APP = REPO / "site" / "src" / "app" / "research"
ARTICLES_TS = REPO / "site" / "src" / "lib" / "articles.ts"

TEMPLATE = '''import type {{ Metadata }} from "next";
import {{ CategoryView }} from "@/components/research/CategoryView";

/* GENERATED by quant/gen_category_pages.py — edit CategoryView, not this. */

export const metadata: Metadata = {{
  title: "{name} — Research — pyportfolios",
  description: "{blurb}",
}};

export default function Page() {{
  return <CategoryView category="{slug}" />;
}}
'''


def main() -> None:
    src = ARTICLES_TS.read_text(encoding="utf-8")

    cats = re.findall(
        r'"([a-z-]+)": \{\s*slug: "[a-z-]+",\s*/\*[^*]*\*/\s*numeral: "[IVX]+",\s*name: "([^"]+)",\s*blurb: "([^"]+)"',
        src,
    )
    if not cats:  # fall back to a looser shape
        cats = re.findall(r'slug: "([a-z-]+)",\s*(?:/\*.*?\*/\s*)?numeral: "[IVX]+",\s*name: "([^"]+)",\s*blurb: "([^"]+)"', src, re.S)
    if len(cats) != 4:
        raise SystemExit(f"expected 4 categories, parsed {len(cats)}")

    article_slugs = set(re.findall(r'^\s{4}slug: "([a-z0-9-]+)",\n\s{4}(?:hero|category):', src, re.M))
    for slug, _, _ in cats:
        if slug in article_slugs:
            raise SystemExit(f"category slug '{slug}' collides with an article slug")

    for slug, name, blurb in cats:
        d = APP / slug
        d.mkdir(parents=True, exist_ok=True)
        (d / "page.tsx").write_text(
            TEMPLATE.format(slug=slug, name=name, blurb=blurb.replace('"', "'")),
            encoding="utf-8",
        )
        print(f"ok  /research/{slug}")
    print(f"\n{len(cats)} category pages generated (no collision with {len(article_slugs)} article slugs)")


if __name__ == "__main__":
    main()
