"""
gen_nginx_configs.py - regenerate every deploy/nginx-<port>.conf from one shape.

Each config is a thin wrapper: process settings + an http block that includes
the vendored mime.types and the shared server body (deploy/nginx-common.conf).
All paths are RELATIVE and resolve against nginx's -p prefix, so the configs
are clone- and machine-independent.

Run:  python quant/gen_nginx_configs.py
Then: powershell -File deploy/run-nginx.ps1 -Port 8080
"""

from __future__ import annotations

from pathlib import Path

DEPLOY = Path(__file__).resolve().parent.parent / "deploy"

# port -> (config filename, extra listen lines, note)
CONFIGS = {
    8080: ("nginx-8080.conf", [], "public — commonly allowed through corporate firewalls"),
    8000: ("nginx-8000.conf", [], "public — alternate"),
    8081: ("nginx-pyportfolios.conf", [], "named instance"),
    5000: ("nginx-5000.conf", [], "local dev"),
    5500: ("nginx-local-5500.conf", ["listen       80;"], "local dev — also answers on :80"),
    5501: ("nginx-local-5501.conf", [], "local dev"),
    1133: ("nginx-1133.conf", [], "local dev"),
}

TEMPLATE = """# Isolated nginx instance for the pyportfolios static export on :{port} ({note}).
#
# Machine-independent: every path below is relative to nginx's prefix, which is
# passed with -p and must be <repo>/deploy/nginx-runtime-{port}/.
# Routing (including the /api proxy) is shared — see deploy/nginx-common.conf.
#
# Start:   powershell -File deploy/run-nginx.ps1 -Port {port}
# Or:      nginx.exe -p <repo>/deploy/nginx-runtime-{port}/ -c <repo>/deploy/{fname}
# Stop:    ...same... -s stop      Reload: ...same... -s reload
#
# GENERATED by quant/gen_nginx_configs.py — edit that or nginx-common.conf.
worker_processes  1;
error_log  logs/error.log warn;
pid        logs/nginx.pid;

events {{
    worker_connections  1024;
}}

http {{
    # NOTE: `include` resolves relative to THIS FILE's directory (deploy/),
    # while root/alias/logs/temp resolve relative to nginx's -p prefix
    # (deploy/nginx-runtime-{port}/). Two different bases - do not "fix" one
    # to match the other.
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;
    server_tokens off;

    access_log            logs/access.log;
    client_body_temp_path temp/client;
    proxy_temp_path       temp/proxy;
    fastcgi_temp_path     temp/fastcgi;
    uwsgi_temp_path       temp/uwsgi;
    scgi_temp_path        temp/scgi;

    server {{
        # Bound on all interfaces so the site is reachable at http://<host>:{port}
        listen       {port};
{extra}        server_name  _;

        include nginx-common.conf;
    }}
}}
"""


def main() -> None:
    for port, (fname, extra, note) in CONFIGS.items():
        extra_lines = "".join(f"        {line}\n" for line in extra)
        (DEPLOY / fname).write_text(
            TEMPLATE.format(port=port, fname=fname, note=note, extra=extra_lines),
            encoding="utf-8",
        )
        # runtime dirs nginx will not create itself
        for sub in ("logs", "temp"):
            (DEPLOY / f"nginx-runtime-{port}" / sub).mkdir(parents=True, exist_ok=True)
        print(f"ok  {fname:26s} -> prefix deploy/nginx-runtime-{port}/")
    print(f"\n{len(CONFIGS)} configs regenerated; all share ../nginx-common.conf")


if __name__ == "__main__":
    main()
