"""Shared chart identity for the PyPortfolios research notes.

Every figure in every note is drawn through this module so the whole set reads
as one publication. The palette is not invented: it was sampled out of the
reference note's own figures (white ground, navy #1a2c5b primary, ochre
#c49a2c secondary, #e6e6e6 grid, #aaaaaa axes, #6b6b6b labels), and the
typeface is the document's own TeX Gyre Heros.

Chart data comes from the article's data module under
site/src/content/articles/data/ -- the same file the site's ECharts components
render, generated by the quant pipeline from real computed results. Nothing is
invented here; load_data() just reads those numbers.
"""
import io
import json
import os
import re

import matplotlib
matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib import font_manager

# ----------------------------------------------------------------- palette ---
NAVY = "#1a2c5b"
OCHRE = "#c49a2c"
GRID = "#e6e6e6"
AXIS = "#aaaaaa"
MUTED = "#6b6b6b"
INK = "#1a1a1a"
PATHGREY = "#c8c8c8"
CREAM = "#f2f0eb"

# A third and fourth hue only where a chart genuinely needs to separate more
# than two series; both are desaturated to sit beside navy and ochre.
SLATE = "#5a6b8c"
CLAY = "#9c6b4f"

SERIES = [NAVY, OCHRE, SLATE, CLAY]

# The notes set figures at the full 532.8bp measure = 7.4in, so a 7.4in-wide
# figure maps 1:1 onto the page and chart point sizes equal page point sizes.
WIDTH = 7.4
DPI = 200

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
DATA_DIR = os.path.join(REPO, "site", "src", "content", "articles", "data")


def _register_fonts():
    base = os.path.join(os.environ.get("APPDATA", ""), "MiKTeX", "fonts",
                        "opentype", "public", "tex-gyre")
    for name in ("texgyreheros-regular.otf", "texgyreheros-bold.otf",
                 "texgyreheros-italic.otf"):
        p = os.path.join(base, name)
        if os.path.exists(p):
            font_manager.fontManager.addfont(p)


_register_fonts()

plt.rcParams.update({
    "font.family": "TeX Gyre Heros",
    "font.size": 7,
    "axes.titlesize": 8.5,
    "axes.labelsize": 7.5,
    "xtick.labelsize": 7,
    "ytick.labelsize": 7,
    "legend.fontsize": 7,
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "savefig.facecolor": "white",
    "axes.edgecolor": AXIS,
    "axes.labelcolor": MUTED,
    "xtick.color": AXIS,
    "ytick.color": AXIS,
    "text.color": INK,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.linewidth": 0.6,
    "axes.grid": True,
    "axes.axisbelow": True,
    "grid.color": GRID,
    "grid.linewidth": 0.5,
    "legend.frameon": False,
    "xtick.major.width": 0.6,
    "ytick.major.width": 0.6,
    "xtick.major.size": 2.5,
    "ytick.major.size": 2.5,
})


def load_data(module):
    """Read a site data module (const data = {...} as const) as a dict."""
    path = os.path.join(DATA_DIR, module + ".ts")
    src = io.open(path, encoding="utf-8").read()
    m = re.search(r"const data\s*=\s*(\{.*?\})\s*(?:as const)?\s*;\s*"
                  r"(?:export default data)", src, re.S)
    if not m:
        raise ValueError("could not parse data module: %s" % path)
    return json.loads(m.group(1))


def style(ax, xgrid=False, ygrid=True):
    """House axis treatment: muted tick labels, horizontal rules only."""
    for lbl in ax.get_xticklabels() + ax.get_yticklabels():
        lbl.set_color(MUTED)
    ax.grid(axis="x", visible=xgrid)
    ax.grid(axis="y", visible=ygrid)


def finish(fig, outdir, name, pad=0.3):
    os.makedirs(outdir, exist_ok=True)
    fig.tight_layout(pad=pad)
    path = os.path.join(outdir, name)
    fig.savefig(path, dpi=DPI)
    plt.close(fig)
    return path


def figure(height):
    """A full-measure figure of the given height in inches."""
    return plt.subplots(figsize=(WIDTH, height))


def diverging():
    """Ochre - white - navy, for correlation matrices and other signed scales.

    Built from the house pair rather than a stock matplotlib map so heatmaps
    belong to the same publication as the line and bar charts. Zero sits on
    white, so sign reads instantly and magnitude reads as saturation.
    """
    from matplotlib.colors import LinearSegmentedColormap
    return LinearSegmentedColormap.from_list(
        "pq_diverging", [OCHRE, "#f2ece0", "#ffffff", "#c9d0dd", NAVY])


def sequential():
    """White - navy, for unsigned magnitude scales."""
    from matplotlib.colors import LinearSegmentedColormap
    return LinearSegmentedColormap.from_list(
        "pq_sequential", ["#ffffff", "#c9d0dd", NAVY])


def annotate_cells(ax, values, fmt="%.2f", threshold=0.78, size=6.2):
    # 0.78, not 0.55: mid-tone cells (a 0.55-0.75 correlation) are still light
    # enough that white ink on them is hard to read at 6pt on paper.
    """Write each cell's value, flipping to white ink on dark grounds."""
    import numpy as _np
    v = _np.asarray(values, dtype=float)
    lo, hi = v.min(), v.max()
    for i in range(v.shape[0]):
        for j in range(v.shape[1]):
            norm = (v[i, j] - lo) / (hi - lo) if hi > lo else 0.0
            ax.text(j, i, fmt % v[i, j], ha="center", va="center",
                    fontsize=size,
                    color="white" if norm > threshold else INK)
