"""Charts for the Black-Scholes & the Greeks note.

Both figures are drawn from the article's own data module,
site/src/content/articles/data/black-scholes-and-the-greeks.ts — the same file
the site's ECharts components render, generated by the quant pipeline from real
computed results. No values are recomputed or invented here.

Figures mirror the article's two <Line> charts:
  4.2  Delta and Gamma across strikes  (greeksCurve)
  4.3  Call value vs time to expiry    (maturity)
"""
import os

import housestyle as hs

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "black-scholes-greeks")
d = hs.load_data("black-scholes-and-the-greeks")

# ------------------------------------- 4.2 the Greeks across strikes ---------
g = d["greeksCurve"]
m = g["m"]
# the article plots gamma scaled by 100 so it shares an axis with delta
gamma100 = [x * 100 for x in g["gamma"]]

fig, ax = hs.figure(2.05)
ax.plot(m, g["delta"], color=hs.NAVY, lw=1.4, label="Delta")
ax.plot(m, gamma100, color=hs.OCHRE, lw=1.4, label="Gamma (×100)")
ax.set_xlabel("Moneyness  K / S")
ax.set_ylabel("Delta · Gamma (×100)")
ax.set_xlim(min(m), max(m))
ax.legend(loc="upper right", handlelength=1.8, borderpad=0.2)
hs.style(ax)
hs.finish(fig, OUT, "fig1-greeks.png")

# ------------------------------------ 4.3 call value vs time to expiry -------
mt = d["maturity"]
t = mt["t"]

fig, ax = hs.figure(2.05)
ax.plot(t, mt["callAtm"], color=hs.NAVY, lw=1.4, label="At the money")
ax.plot(t, mt["callOtm5"], color=hs.OCHRE, lw=1.4, ls="--", label="5% out of the money")
ax.set_xlabel("Time to expiry (years)")
ax.set_ylabel("Call value (USD)")
ax.set_xlim(min(t), max(t))
ax.legend(loc="upper left", handlelength=1.8, borderpad=0.2)
hs.style(ax)
hs.finish(fig, OUT, "fig2-decay.png")

print("wrote fig1-greeks.png, fig2-decay.png")
print("  greeksCurve points: %d   maturity points: %d" % (len(m), len(t)))
print("  ATM call at %.2fy = %.2f ; at %.2fy = %.2f"
      % (t[0], mt["callAtm"][0], t[-1], mt["callAtm"][-1]))
