import type { Metadata } from "next";
import { CategoryView } from "@/components/research/CategoryView";

/* GENERATED by quant/gen_category_pages.py — edit CategoryView, not this. */

export const metadata: Metadata = {
  title: "Algorithmic Trading — Research — pyportfolios",
  description: "Signals, backtests, and the discipline that separates edge from artefact.",
};

export default function Page() {
  return <CategoryView category="algorithmic-trading" />;
}
