/* FAQ — native <details> accordion: progressive disclosure, near-zero JS, fully
   keyboard-accessible. Answers the objections that stop a visitor signing up. */

import type { CSSProperties } from "react";

const FAQS = [
  {
    q: "Do I need to be a quant already?",
    a: "No — but you should be comfortable writing code. We build from first principles and explain the mathematics rather than assume it.",
  },
  {
    q: "What do I need installed?",
    a: "Python and the standard scientific stack (NumPy, pandas, SciPy, matplotlib). Every notebook is self-contained and lists exactly what it needs.",
  },
  {
    q: "Will the notebooks run on my machine?",
    a: "Yes. They are written to run on Windows and macOS alike, with seeded synthetic data so they work offline, out of the box — then swap in live data when you want.",
  },
  {
    q: "How is this different from a YouTube course?",
    a: "Reproducibility. Every figure and number on the site is generated by code you can download, change, and re-run on real market data — not a screen recording you can only watch.",
  },
  {
    q: "What level is the material?",
    a: "Academic models — Black–Scholes, Ledoit–Wolf shrinkage, Extreme Value Theory, Hierarchical Risk Parity — implemented empirically and stress-tested, never hand-waved.",
  },
  {
    q: "Is it free?",
    a: "The fundamentals and every notebook are free to run. The full library and the course are part of Pro, which is coming soon — join early access to be first in.",
  },
];

export function FAQ() {
  return (
    <section id="faq" className="scroll-mt-20 border-b border-pearl/10 bg-navy-elevated/40">
      <div className="mx-auto max-w-3xl px-6 py-28 md:py-32">
        <div data-reveal className="mb-12 flex items-center gap-4 border-b border-pearl/10 pb-4">
          <span className="h-px w-8 bg-aqua/50" aria-hidden="true" />
          <h2 className="t-mono text-sm uppercase tracking-[0.24em] text-mist">Frequently asked</h2>
        </div>

        <div data-reveal className="divide-y divide-pearl/10 border-y border-pearl/10">
          {FAQS.map((f, i) => (
            <details key={f.q} className="faq-item group" style={{ "--reveal-delay": `${i * 40}ms` } as CSSProperties}>
              <summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-5 text-left">
                <span className="font-serif text-lg text-pearl transition-colors group-open:text-aqua md:text-xl">{f.q}</span>
                <span className="faq-mark relative h-4 w-4 shrink-0 text-mist" aria-hidden="true" />
              </summary>
              <p className="pb-6 pr-10 leading-relaxed text-mist">{f.a}</p>
            </details>
          ))}
        </div>
      </div>
    </section>
  );
}
