import type { Metadata } from "next";
import { CategoryView } from "@/components/research/CategoryView";

/* GENERATED by quant/gen_category_pages.py — edit CategoryView, not this. */

export const metadata: Metadata = {
  title: "Portfolio Optimization — Research — pyportfolios",
  description: "Turning noisy forecasts into allocations that survive out-of-sample.",
};

export default function Page() {
  return <CategoryView category="portfolio-optimization" />;
}
