import type { Metadata } from "next";
import { CategoryView } from "@/components/research/CategoryView";

/* GENERATED by quant/gen_category_pages.py — edit CategoryView, not this. */

export const metadata: Metadata = {
  title: "Risk Management — Research — pyportfolios",
  description: "Measuring — and respecting — the tails.",
};

export default function Page() {
  return <CategoryView category="risk-management" />;
}
